<?php
if (!defined('ABSPATH')) exit;

trait SENuke_AI_Backups {
    public static function create_backup(WP_REST_Request $request) {
        $data=$request->get_json_params();$backup_id=sanitize_key('senuke-'.gmdate('Ymd-His').'-'.wp_generate_password(6,false,false));$theme=wp_get_theme();$menus=[];
        foreach(['SENuke Primary Navigation','SENuke Footer Navigation'] as $menu_name){$menu=wp_get_nav_menu_object($menu_name);$items=[];if($menu)foreach(wp_get_nav_menu_items((int)$menu->term_id)?:[] as $item)$items[]=['id'=>(int)$item->ID,'title'=>(string)$item->title,'url'=>(string)$item->url,'parent'=>(int)$item->menu_item_parent,'position'=>(int)$item->menu_order];$menus[$menu_name]=['existed'=>(bool)$menu,'items'=>$items];}
        $meta_keys=['_senuke_meta_title','_senuke_meta_description','_senuke_canonical_url','_senuke_schema_json','_senuke_aeo_reviewed','_senuke_geo_reviewed','_senuke_release_id','_senuke_snapshot_hash','_senuke_page_id'];$page_seo=[];
        foreach(get_posts(['post_type'=>['page','post'],'post_status'=>'any','numberposts'=>-1,'fields'=>'ids']) as $page_id){$saved=[];foreach($meta_keys as $key)$saved[$key]=metadata_exists('post',$page_id,$key)?get_post_meta($page_id,$key,true):null;$page_seo[(string)$page_id]=$saved;}
        $snapshot=['backupId'=>$backup_id,'createdAt'=>gmdate('c'),'releaseId'=>sanitize_text_field($data['releaseId']??''),'snapshotHash'=>sanitize_text_field($data['snapshotHash']??''),'site'=>['blogname'=>get_option('blogname'),'blogdescription'=>get_option('blogdescription'),'show_on_front'=>get_option('show_on_front'),'page_on_front'=>(int)get_option('page_on_front'),'page_for_posts'=>(int)get_option('page_for_posts'),'permalink_structure'=>get_option('permalink_structure')],'theme'=>['stylesheet'=>$theme->get_stylesheet(),'template'=>$theme->get_template(),'version'=>$theme->get('Version')],'activePlugins'=>get_option('active_plugins',[]),'navigationLocations'=>get_theme_mod('nav_menu_locations',[]),'managedMenus'=>$menus,'pageSeo'=>$page_seo,'designPackage'=>get_option(self::STYLE_OPTION,[]),'forms'=>get_option(self::FORM_OPTION,[]),'identity'=>get_option(self::IDENTITY_OPTION,[])];
        $backups=get_option(self::BACKUP_OPTION,[]);if(!is_array($backups))$backups=[];$backups[$backup_id]=$snapshot;if(count($backups)>20)$backups=array_slice($backups,-20,null,true);update_option(self::BACKUP_OPTION,$backups,false);return rest_ensure_response(['backupId'=>$backup_id,'createdAt'=>$snapshot['createdAt'],'scope'=>['site_settings','theme_identity','navigation','page_seo','forms','design_package','site_identity']]);
    }

    public static function restore_backup(WP_REST_Request $request) {
        $backup_id=sanitize_key($request['id']);$backups=get_option(self::BACKUP_OPTION,[]);$snapshot=is_array($backups)?($backups[$backup_id]??null):null;if(!$snapshot)return new WP_Error('senuke_backup_not_found','The requested SENuke deployment backup was not found.',['status'=>404]);
        foreach((array)($snapshot['site']??[]) as $key=>$value)update_option(sanitize_key($key),$value);$previous=sanitize_key($snapshot['theme']['stylesheet']??'');if($previous&&wp_get_theme($previous)->exists()&&wp_get_theme()->get_stylesheet()!==$previous&&current_user_can('switch_themes'))switch_theme($previous);set_theme_mod('nav_menu_locations',(array)($snapshot['navigationLocations']??[]));update_option(self::STYLE_OPTION,(array)($snapshot['designPackage']??[]),false);update_option(self::FORM_OPTION,(array)($snapshot['forms']??[]),false);update_option(self::IDENTITY_OPTION,(array)($snapshot['identity']??[]),false);
        foreach((array)($snapshot['managedMenus']??[]) as $menu_name=>$menu_snapshot)self::restore_menu($menu_name,$menu_snapshot);
        $meta_keys=['_senuke_meta_title','_senuke_meta_description','_senuke_canonical_url','_senuke_schema_json','_senuke_aeo_reviewed','_senuke_geo_reviewed','_senuke_release_id','_senuke_snapshot_hash','_senuke_page_id'];foreach((array)($snapshot['pageSeo']??[]) as $page_id=>$saved_values){$saved=(array)$saved_values;foreach($meta_keys as $key){if(array_key_exists($key,$saved)&&$saved[$key]!==null)update_post_meta($page_id,$key,$saved[$key]);else delete_post_meta($page_id,$key);}}
        flush_rewrite_rules(false);return rest_ensure_response(['restored'=>true,'backupId'=>$backup_id,'restoredAt'=>gmdate('c'),'scope'=>['site_settings','theme_identity','navigation','page_seo','forms','design_package','site_identity']]);
    }

    private static function restore_menu($name,$snapshot) {
        $name=sanitize_text_field($name);$snapshot=(array)$snapshot;$menu=wp_get_nav_menu_object($name);if(empty($snapshot['existed'])){if($menu)wp_delete_nav_menu((int)$menu->term_id);return;}$menu_id=$menu?(int)$menu->term_id:wp_create_nav_menu($name);if(is_wp_error($menu_id))return;foreach(wp_get_nav_menu_items($menu_id)?:[] as $item)wp_delete_post($item->ID,true);$restored=[];$pending=array_values((array)($snapshot['items']??[]));
        for($pass=0;$pass<100&&$pending;$pass++){$remaining=[];foreach($pending as $item){$old=(int)($item['id']??0);$parent=(int)($item['parent']??0);if($parent&&empty($restored[$parent])){$remaining[]=$item;continue;}$new=wp_update_nav_menu_item($menu_id,0,['menu-item-title'=>sanitize_text_field($item['title']??'Page'),'menu-item-url'=>esc_url_raw($item['url']??home_url('/')),'menu-item-parent-id'=>$parent?(int)$restored[$parent]:0,'menu-item-status'=>'publish','menu-item-position'=>(int)($item['position']??0)]);if(!is_wp_error($new)&&$old)$restored[$old]=(int)$new;}if(count($remaining)===count($pending))break;$pending=$remaining;}
    }
}
