import { beforeEach, expect, it, vi } from 'vitest';
const mock = vi.hoisted(() => ({executionTask:{findMany:vi.fn()},project:{findUniqueOrThrow:vi.fn()},websiteApprovedRelease:{findMany:vi.fn()},seoFixQueueItem:{findMany:vi.fn()},workspaceActivity:{findFirst:vi.fn()},$transaction:vi.fn()}));
vi.mock('./index.js',()=>({prisma:mock}));
import { reconcileProjectPlanning } from './planning-reconciliation.js';
beforeEach(()=>{vi.resetAllMocks();mock.project.findUniqueOrThrow.mockResolvedValue({websiteUrl:'https://example.com'});mock.websiteApprovedRelease.findMany.mockResolvedValue([]);mock.seoFixQueueItem.findMany.mockResolvedValue([]);});
const plan = {id:'plan',status:'completed',approvalSnapshotJson:{contentPlanStatus:'approved',approvedAt:'2026-09-01',contentPlan:{pageAssignments:[{targetUrl:'/service',pagePurpose:'Explain service',canonicalKeyword:'service'}]}}};
it('does not complete tasks just because a website exists',async()=>{mock.executionTask.findMany.mockResolvedValue([{id:'task',status:'ready',title:'Create page'}]);expect((await reconcileProjectPlanning('p',false)).changes).toEqual([]);expect(mock.$transaction).not.toHaveBeenCalled();});
it('matches approved page assignments to older mapping tasks only',async()=>{mock.executionTask.findMany.mockResolvedValue([plan,{id:'mapping',status:'ready',sourceType:'seo_fix_queue_item',sourceId:'fix',moduleName:'keyword_research',createdAt:new Date('2026-08-01'),description:'Assign a page purpose',title:'Map page'},{id:'new-finding',status:'ready',sourceType:'seo_fix_queue_item',sourceId:'fix',moduleName:'keyword_research',createdAt:new Date('2026-09-02'),description:'Assign a page purpose'}]);mock.seoFixQueueItem.findMany.mockResolvedValue([{id:'fix',affectedUrl:'https://example.com/service/'}]);expect((await reconcileProjectPlanning('p',false)).changes.map(c=>c.id)).toEqual(['mapping']);});
it('does not complete publishing or repair work from plan approval',async()=>{mock.executionTask.findMany.mockResolvedValue([plan,{id:'publish',status:'pending',sourceType:'content_plan_publishing'},{id:'repair',status:'ready',sourceType:'next_best_action',title:'Canonical intent ownership and page repair',description:'Repair titles and recrawl after publication'}]);expect((await reconcileProjectPlanning('p',false)).changes).toEqual([]);});
it('recognizes an approved website review and is read-only in dry run',async()=>{mock.executionTask.findMany.mockResolvedValue([plan,{id:'review',title:'Review website',sourceType:'website_builder_review',sourceId:'build',status:'ready_to_publish'}]);mock.websiteApprovedRelease.findMany.mockResolvedValue([{id:'release',buildId:'build'}]);expect((await reconcileProjectPlanning('p',false)).changes.map(c=>c.id)).toEqual(['review']);expect(mock.$transaction).not.toHaveBeenCalled();});

it('recognizes website approval even when no SEO plan is present',async()=>{mock.executionTask.findMany.mockResolvedValue([{id:'review',title:'Review website',sourceType:'website_builder_review',sourceId:'build',status:'ready_to_publish'}]);mock.websiteApprovedRelease.findMany.mockResolvedValue([{id:'release',buildId:'build'}]);expect((await reconcileProjectPlanning('p',false)).changes.map(c=>c.id)).toEqual(['review']);});
