import { useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";
import { api } from "../api.js";
import { Card } from "./ui.js";
import type { DiscoveryIdea } from "./AdaptiveBusinessDiscovery.js";

type Props = {
  draftId: string;
  ideas: DiscoveryIdea[];
  busy: string;
  feedbackByIdea: Record<string, string>;
  onFeedback: (ideaId: string, value: string) => void;
  onRegenerate: () => void;
  onFineTune: (idea: DiscoveryIdea, instruction: string) => void;
  onSave: (idea: DiscoveryIdea) => void;
  onReject: (idea: DiscoveryIdea) => void;
  onUse: (idea: DiscoveryIdea) => void;
};

const record = (value: unknown) => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
const rows = (value: unknown) => Array.isArray(value) ? value.map(record) : [];
const strings = (value: unknown) => Array.isArray(value) ? value.map(String).filter(Boolean) : [];
const show = (value: unknown, fallback = "Not established yet") => typeof value === "string" && value.trim() ? value : value == null ? fallback : String(value);

export default function DiscoveryIdeaTabs(props: Props) {
  const [activeId, setActiveId] = useState(props.ideas.find((idea) => idea.status !== "REJECTED")?.id ?? props.ideas[0]?.id ?? "");
  const [downloadingId, setDownloadingId] = useState("");
  const [downloadError, setDownloadError] = useState("");
  useEffect(() => { if (!props.ideas.some((idea) => idea.id === activeId)) setActiveId(props.ideas.find((idea) => idea.status !== "REJECTED")?.id ?? props.ideas[0]?.id ?? ""); }, [activeId, props.ideas]);
  const idea = useMemo(() => props.ideas.find((item) => item.id === activeId) ?? props.ideas[0], [activeId, props.ideas]);
  if (!idea) return null;
  const details = record(idea.detailsJson);
  const canvas = record(details.businessModelCanvas);
  const constraints = rows(details.keyConstraints);
  const roleRequirements = record(details.roleRequirements);
  const requiredRoles = rows(roleRequirements.roles);
  const transaction = record(details.transactionFlow);
  const transactionSteps = rows(transaction.steps);
  const modules = rows(details.essentialModules);
  const risks = rows(details.riskRegister);
  const positioning = record(details.initialProductPositioning);
  const pros = rows(details.pros);
  const cons = rows(details.cons);
  const competitors = rows(details.competitors);
  const compliance = rows(details.compliance);
  const workflow = rows(details.validationWorkflow);
  const launch = record(details.launchStrategy);
  const launchPhases = rows(launch.phases);
  const hasExpandedBrief = Object.keys(details).length > 0;
  const instruction = props.feedbackByIdea[idea.id] || "";

  const download = async () => {
    setDownloadingId(idea.id); setDownloadError("");
    try { await api.download(`/api/discovery-drafts/${props.draftId}/ideas/${idea.id}/download`); }
    catch (error) { setDownloadError(error instanceof Error ? error.message : "The PDF could not be downloaded."); }
    finally { setDownloadingId(""); }
  };

  return <section className="space-y-4">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-wide text-violet-700">Business Idea Briefs</div><h2 className="mt-1 text-2xl font-black text-slate-950">Compare complete business models</h2><p className="mt-1 text-xs leading-5 text-slate-500">Open each tab to review positioning, constraints, roles, transaction flow, essential modules, risks, competitors, validation, and launch strategy.</p></div><button type="button" onClick={props.onRegenerate} disabled={Boolean(props.busy)} className="rounded-lg border bg-white px-4 py-2 text-xs font-black text-slate-700 disabled:opacity-50">Generate a different set</button></div>

    <div role="tablist" aria-label="Generated business ideas" className="grid gap-2 rounded-2xl border bg-slate-100 p-2 md:grid-cols-3">{props.ideas.map((item, index) => <button key={item.id} type="button" role="tab" aria-selected={item.id === idea.id} onClick={() => setActiveId(item.id)} className={`rounded-xl px-4 py-3 text-left transition ${item.id === idea.id ? "bg-slate-950 text-white shadow-lg" : "bg-white text-slate-700 hover:bg-slate-50"}`}><div className="flex items-center justify-between gap-3"><span className="text-[9px] font-black uppercase tracking-wide opacity-70">Idea {index + 1}</span><span className={`rounded-full px-2 py-0.5 text-[9px] font-black uppercase ${item.id === idea.id ? "bg-white/15" : item.status === "SAVED" ? "bg-emerald-100 text-emerald-800" : item.status === "REJECTED" ? "bg-rose-100 text-rose-700" : "bg-violet-50 text-violet-700"}`}>{item.status}</span></div><div className="mt-1 line-clamp-2 text-sm font-black leading-5">{item.title}</div><div className="mt-2 text-[10px] opacity-70">{item.confidence ?? "-"}% directional fit</div></button>)}</div>

    <div role="tabpanel"><Card className="overflow-hidden">
      <div className="bg-slate-950 px-5 py-6 text-white sm:px-7"><div className="flex flex-wrap items-start justify-between gap-4"><div className="max-w-3xl"><div className="text-[10px] font-black uppercase tracking-[0.15em] text-emerald-300">Selected business idea</div><h3 className="mt-2 text-2xl font-black sm:text-3xl">{idea.title}</h3><p className="mt-3 text-sm leading-6 text-slate-300">{idea.description}</p></div><div className="rounded-2xl bg-white/10 px-5 py-4 text-center"><div className="text-2xl font-black text-emerald-300">{idea.confidence ?? "-"}</div><div className="text-[9px] font-black uppercase tracking-wide text-slate-300">Directional fit / 100</div></div></div><div className="mt-5 flex flex-wrap gap-2"><span className="rounded-full bg-white/10 px-3 py-1 text-xs font-bold">{show(idea.businessModel, "Business model pending")}</span><span className="rounded-full bg-white/10 px-3 py-1 text-xs font-bold">Difficulty: {show(idea.difficulty)}</span><span className="rounded-full bg-white/10 px-3 py-1 text-xs font-bold">{show(idea.timeCostBand)}</span></div></div>

      <div className="space-y-7 p-5 sm:p-7">
        {!hasExpandedBrief && <div className="rounded-2xl border border-violet-200 bg-violet-50 p-4 text-sm leading-6 text-violet-950"><b>This saved idea predates the expanded Business Idea Brief.</b> Generate a different set or fine-tune this idea to add positioning, roles, transaction flow, modules, risks, competitors, compliance, and launch strategy.</div>}
        <div className="grid gap-4 lg:grid-cols-2"><Detail label="Why this idea fits" value={idea.whyFit} tone="emerald" /><Detail label="Problem it targets" value={idea.problemSolved} /><Detail label="Target customer" value={idea.targetAudience} /><Detail label="How it makes money" value={idea.revenueModel} /></div>

        <section className="rounded-2xl border-2 border-amber-300 bg-amber-50 p-5"><div className="flex items-center justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-[0.14em] text-amber-700">Important before proceeding</div><h4 className="mt-1 text-lg font-black text-amber-950">Key constraints</h4></div><span className="rounded-full bg-white px-3 py-1 text-xs font-black text-amber-800">{constraints.length || "Review"}</span></div><div className="mt-4 grid gap-3 lg:grid-cols-2">{constraints.length ? constraints.map((item, index) => <div key={`${show(item.constraint)}-${index}`} className="rounded-xl border border-amber-200 bg-white p-4"><div className="font-black text-amber-950">{show(item.constraint, `Constraint ${index + 1}`)}</div><p className="mt-2 text-xs leading-5 text-slate-600"><b>Impact:</b> {show(item.impact)}</p><p className="mt-2 text-xs leading-5 text-emerald-800"><b>Response:</b> {show(item.response)}</p></div>) : <p className="text-sm leading-6 text-amber-900">Confirm time, budget, skills, geography, operating capacity, and applicable rules before committing.</p>}</div></section>

        <section className="rounded-2xl border-2 border-violet-300 bg-violet-50 p-5"><div className="text-[10px] font-black uppercase tracking-[0.14em] text-violet-700">Recommended initial product positioning</div><blockquote className="mt-3 border-l-4 border-violet-600 pl-4 text-base font-black leading-7 text-slate-950">{show(positioning.positioningStatement, "Fine-tune or regenerate this idea to produce a positioning statement.")}</blockquote><div className="mt-4 grid gap-3 md:grid-cols-2"><Detail label="Category" value={positioning.category || idea.businessModel} /><Detail label="First audience" value={positioning.firstAudience || idea.targetAudience} /><Detail label="Urgent problem" value={positioning.urgentProblem || idea.problemSolved} /><Detail label="Initial promise" value={positioning.promise} /><Detail label="Why it is different" value={positioning.differentiation} /><ListPanel title="Proof needed" items={positioning.proofNeeded} /></div>{strings(positioning.claimsToAvoid).length > 0 && <div className="mt-4 rounded-xl border border-amber-200 bg-white p-4"><div className="text-xs font-black text-amber-900">Claims to avoid until supported</div><p className="mt-2 text-xs leading-5 text-slate-600">{strings(positioning.claimsToAvoid).join(" · ")}</p></div>}</section>

        <section className="rounded-2xl border-2 border-sky-300 bg-sky-50 p-5"><div className="text-[10px] font-black uppercase tracking-[0.14em] text-sky-700">Major feasibility decision</div><h4 className="mt-1 text-lg font-black text-sky-950">Roles & capability requirements</h4><div className="mt-4 grid gap-3 md:grid-cols-2"><Detail label="Owner's role" value={roleRequirements.ownerRole} /><Detail label="Lean team recommendation" value={roleRequirements.leanTeamRecommendation} /><Detail label="First hiring / contracting decision" value={roleRequirements.firstHiringDecision} /><ListPanel title="Capability gaps to validate" items={roleRequirements.skillGaps} /></div><div className="mt-4 grid gap-3 lg:grid-cols-2">{requiredRoles.map((item, index) => <div key={`${show(item.role)}-${index}`} className="rounded-xl border border-sky-200 bg-white p-4"><div className="flex items-center justify-between gap-2"><h5 className="font-black text-slate-950">{show(item.role)}</h5>{item.mustHave === true && <span className="rounded-full bg-sky-700 px-2 py-1 text-[9px] font-black uppercase text-white">Essential</span>}</div><p className="mt-2 text-xs leading-5 text-slate-600">{show(item.whyNeeded)}</p><div className="mt-3 grid gap-2 text-[10px] text-slate-600 sm:grid-cols-3"><span><b>When:</b> {show(item.timing)}</span><span><b>Commitment:</b> {show(item.commitment)}</span><span><b>Cover with:</b> {show(item.coverage)}</span></div></div>)}</div></section>

        <Section title="Business model canvas" eyebrow="How the idea works"><div className="grid gap-3 md:grid-cols-2"><Detail label="Customer" value={canvas.customer || idea.targetAudience} /><Detail label="Payer" value={canvas.payer} /><Detail label="Value proposition" value={canvas.valueProposition} /><Detail label="Offer" value={canvas.offer} /><Detail label="Delivery model" value={canvas.deliveryModel} /><Detail label="Pricing approach" value={canvas.pricingApproach || idea.revenueModel} /></div><div className="mt-4 grid gap-4 lg:grid-cols-2"><ListPanel title="Acquisition channels" items={canvas.acquisitionChannels} /><ListPanel title="Core costs" items={canvas.coreCosts} /><ListPanel title="Key partners" items={canvas.keyPartners} /><ListPanel title="Key metrics" items={canvas.keyMetrics} /></div></Section>

        <Section title="Customer & transaction flow" eyebrow="How value, work, and money move"><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4"><Detail label="Transaction type" value={transaction.transactionType || idea.revenueModel} /><Detail label="Customer" value={transaction.customer || idea.targetAudience} /><Detail label="Payer" value={transaction.payer} /><Detail label="Provider" value={transaction.provider} /><Detail label="Payment timing" value={transaction.paymentTiming} /><Detail label="Business revenue" value={transaction.platformRevenue || idea.revenueModel} /><Detail label="Fulfilment handoff" value={transaction.fulfilmentHandoff} /><Detail label="Refunds / disputes" value={transaction.refundsAndDisputes} /></div><div className="mt-4 space-y-3">{transactionSteps.length ? transactionSteps.map((item, index) => <div key={`${show(item.action)}-${index}`} className="grid gap-3 rounded-xl border bg-slate-50 p-4 sm:grid-cols-[38px_1fr]"><span className="grid h-9 w-9 place-items-center rounded-full bg-slate-950 text-xs font-black text-white">{index + 1}</span><div><div className="text-xs font-black uppercase tracking-wide text-violet-700">{show(item.actor)}</div><p className="mt-1 text-sm font-bold leading-6 text-slate-800">{show(item.action)}</p><div className="mt-2 flex flex-wrap gap-2 text-[10px] text-slate-600"><span className="rounded-full bg-white px-2 py-1"><b>Record:</b> {show(item.systemRecord, "To define")}</span><span className="rounded-full bg-emerald-50 px-2 py-1 text-emerald-800"><b>Money:</b> {show(item.moneyMovement, "No direct movement at this step")}</span></div></div></div>) : <Empty text="The detailed transaction steps need to be generated or fine-tuned for this idea." />}</div></Section>

        <Section title="Essential requirement modules" eyebrow="What must exist to run the pilot"><div className="grid gap-3 lg:grid-cols-2">{modules.map((item, index) => <div key={`${show(item.module)}-${index}`} className={`rounded-xl border p-4 ${item.priority === "ESSENTIAL_PILOT" ? "border-emerald-300 bg-emerald-50" : "bg-slate-50"}`}><div className="flex flex-wrap items-center justify-between gap-2"><h5 className="font-black text-slate-950">{show(item.module)}</h5><div className="flex gap-2"><span className="rounded-full bg-white px-2 py-1 text-[9px] font-black uppercase text-slate-600">{show(item.priority).replaceAll("_", " ")}</span><span className="rounded-full bg-white px-2 py-1 text-[9px] font-black uppercase text-violet-700">{show(item.deliveryChoice).replaceAll("_", " ")}</span></div></div><p className="mt-2 text-xs leading-5 text-slate-600">{show(item.purpose)}</p><p className="mt-2 text-xs"><b>Required for:</b> {show(item.requiredFor)} · <b>Owner:</b> {show(item.ownerRole)}</p>{strings(item.dependencies).length > 0 && <p className="mt-2 text-[10px] text-slate-500"><b>Depends on:</b> {strings(item.dependencies).join(" · ")}</p>}</div>)}</div></Section>

        <Section title="Pros and cons" eyebrow="Balanced decision view"><div className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><h5 className="font-black text-emerald-900">Pros</h5><DetailList items={pros} empty="No advantages were supplied yet." tone="emerald" /></div><div className="rounded-2xl border border-rose-200 bg-rose-50 p-5"><h5 className="font-black text-rose-900">Cons and trade-offs</h5><DetailList items={cons} empty="No trade-offs were supplied yet." tone="rose" /></div></div></Section>

        <Section title="Competitor landscape" eyebrow="What the customer may choose instead"><div className="grid gap-3 lg:grid-cols-2">{competitors.length ? competitors.map((item, index) => <div key={`${show(item.name)}-${index}`} className="rounded-xl border bg-slate-50 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h5 className="font-black text-slate-950">{show(item.name)}</h5><span className="rounded-full bg-white px-2 py-1 text-[9px] font-black uppercase text-slate-500">{show(item.verification, "REQUIRES_RESEARCH").replaceAll("_", " ")}</span></div><div className="mt-1 text-[10px] font-black uppercase text-violet-700">{show(item.type)}</div><p className="mt-3 text-xs leading-5 text-slate-600">{show(item.whatTheyDo)}</p><p className="mt-2 text-xs leading-5 text-emerald-800"><b>Possible differentiation:</b> {show(item.differentiation)}</p></div>) : <Empty text="Competitors have not been researched yet. Validate direct, indirect, and do-it-yourself alternatives." />}</div></Section>

        <Section title="Risk register" eyebrow="Signals, mitigation, and ownership"><div className="space-y-3">{risks.length ? risks.map((item, index) => <div key={`${show(item.risk)}-${index}`} className={`rounded-xl border p-4 ${item.impact === "HIGH" ? "border-rose-300 bg-rose-50" : "bg-slate-50"}`}><div className="flex flex-wrap items-start justify-between gap-2"><div><div className="text-[9px] font-black uppercase text-slate-500">{show(item.category)}</div><h5 className="mt-1 font-black text-slate-950">{show(item.risk)}</h5></div><div className="flex gap-2"><span className="rounded-full bg-white px-2 py-1 text-[9px] font-black uppercase text-slate-700">Likelihood {show(item.likelihood)}</span><span className="rounded-full bg-white px-2 py-1 text-[9px] font-black uppercase text-rose-700">Impact {show(item.impact)}</span></div></div><div className="mt-3 grid gap-3 md:grid-cols-2"><p className="text-xs leading-5 text-slate-600"><b>Early warning:</b> {show(item.earlyWarning)}</p><p className="text-xs leading-5 text-emerald-800"><b>Mitigation:</b> {show(item.mitigation)}</p></div><p className="mt-2 text-[10px] font-bold text-slate-500">Owner: {show(item.ownerRole)}</p></div>) : <Empty text={idea.majorRisk || "Generate or fine-tune the idea to build its risk register."} />}</div></Section>

        <Section title="Compliance and operating checks" eyebrow="Advisory review checklist"><div className="space-y-3">{compliance.length ? compliance.map((item, index) => <div key={`${show(item.area)}-${index}`} className="rounded-xl border border-amber-200 bg-amber-50 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h5 className="font-black text-slate-950">{show(item.area)}</h5><span className="rounded-full bg-amber-500 px-2 py-1 text-[9px] font-black uppercase text-white">Warning · review in QC</span></div><p className="mt-2 text-xs leading-5 text-slate-600">{show(item.whyItMatters)}</p><p className="mt-2 text-xs font-bold leading-5 text-slate-800">Action: {show(item.action)}</p></div>) : <Empty text="No specific compliance issue was identified. This is not legal clearance; verify the rules applicable to the market and operating model." />}</div><p className="mt-3 text-xs font-semibold text-amber-800">These checks remain visible during website quality review and approval, but they do not stop the workflow.</p></Section>

        <Section title="Small validation workflow" eyebrow="Test before creating the full business"><div className="space-y-3">{(workflow.length ? workflow : strings(idea.validationSteps).map((detail, index) => ({ step: index + 1, title: `Validation step ${index + 1}`, detail, successSignal: "Record evidence before continuing." }))).map((item, index) => <div key={`${show(item.title)}-${index}`} className="grid gap-3 rounded-xl border bg-white p-4 sm:grid-cols-[42px_1fr]"><span className="grid h-10 w-10 place-items-center rounded-full bg-violet-700 text-sm font-black text-white">{show(item.step, String(index + 1))}</span><div><h5 className="font-black text-slate-950">{show(item.title)}</h5><p className="mt-1 text-xs leading-5 text-slate-600">{show(item.detail)}</p><p className="mt-2 text-xs font-bold text-emerald-800">Success signal: {show(item.successSignal)}</p></div></div>)}</div></Section>

        <Section title="Lean launch strategy" eyebrow="Proceed only after validation"><div className="grid gap-3 md:grid-cols-2"><Detail label="Beachhead market" value={launch.beachheadMarket} /><Detail label="Positioning" value={launch.positioning || positioning.positioningStatement} /><Detail label="Launch offer" value={launch.launchOffer} /><Detail label="Budget guardrail" value={launch.budgetGuardrail} /><ListPanel title="Launch channels" items={launch.channels} /><ListPanel title="Go / no-go criteria" items={launch.goNoGoCriteria} /></div><div className="mt-4 grid gap-3 lg:grid-cols-2">{launchPhases.map((item, index) => <div key={`${show(item.phase)}-${index}`} className="rounded-xl border border-violet-200 bg-violet-50 p-4"><div className="text-[9px] font-black uppercase tracking-wide text-violet-700">{show(item.phase, `Phase ${index + 1}`)}</div><h5 className="mt-1 font-black text-slate-950">{show(item.objective)}</h5><ul className="mt-3 space-y-1 text-xs leading-5 text-slate-600">{strings(item.actions).map((action) => <li key={action}>- {action}</li>)}</ul><p className="mt-3 text-xs font-bold text-emerald-800">Success signal: {show(item.successSignal)}</p></div>)}</div></Section>

        <div className="rounded-2xl border border-violet-200 bg-violet-50 p-5"><div className="text-[10px] font-black uppercase tracking-wide text-violet-700">Fine-tune this idea into new options</div><p className="mt-1 text-xs leading-5 text-slate-600">Ask a question or explain what should change. SEnuke will generate three new variations anchored to this idea.</p><textarea rows={3} value={instruction} onChange={(event) => props.onFeedback(idea.id, event.target.value)} placeholder="Example: Make this a subscription for Canadian agencies, reduce the initial cost, and explain the compliance impact." className="mt-3 w-full rounded-xl border bg-white px-3 py-2 text-sm" /><button type="button" disabled={Boolean(props.busy) || instruction.trim().length < 3} onClick={() => props.onFineTune(idea, instruction)} className="mt-3 rounded-lg bg-violet-700 px-4 py-2.5 text-xs font-black text-white disabled:bg-slate-300">Fine-tune & generate 3 refined ideas</button></div>

        {downloadError && <div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs text-rose-800">{downloadError}</div>}
        <div className="grid gap-2 border-t pt-5 sm:grid-cols-4"><button type="button" disabled={Boolean(props.busy) || idea.status === "SAVED"} onClick={() => props.onSave(idea)} className="rounded-lg border bg-white px-3 py-2.5 text-xs font-black text-slate-700 disabled:bg-emerald-50 disabled:text-emerald-700">{idea.status === "SAVED" ? "Saved ✓" : "Save idea"}</button><button type="button" disabled={Boolean(props.busy) || idea.status === "REJECTED"} onClick={() => props.onReject(idea)} className="rounded-lg border border-rose-200 bg-rose-50 px-3 py-2.5 text-xs font-black text-rose-700 disabled:opacity-50">{idea.status === "REJECTED" ? "Rejected ✓" : "Reject"}</button><button type="button" disabled={Boolean(props.busy) || Boolean(downloadingId)} onClick={() => void download()} className="rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-xs font-black text-slate-800 disabled:opacity-50">{downloadingId === idea.id ? "Preparing PDF…" : "Download idea PDF"}</button><button type="button" disabled={Boolean(props.busy) || idea.status === "REJECTED"} onClick={() => props.onUse(idea)} className="rounded-lg bg-emerald-600 px-3 py-2.5 text-xs font-black text-white disabled:bg-slate-300">{props.busy === "convert" ? "Creating Project…" : "Use This Idea"}</button></div>
        <p className="text-center text-[10px] leading-4 text-slate-400">Saving keeps this brief in Discovery. Fine-tuning generates new options. Only Use This Idea creates a Project.</p>
      </div>
    </Card></div>
  </section>;
}

function Section({ title, eyebrow, children }: { title: string; eyebrow: string; children: ReactNode }) { return <section><div className="text-[10px] font-black uppercase tracking-[0.13em] text-violet-700">{eyebrow}</div><h4 className="mt-1 text-xl font-black text-slate-950">{title}</h4><div className="mt-4">{children}</div></section>; }
function Detail({ label, value, tone = "slate" }: { label: string; value: unknown; tone?: "slate" | "emerald" }) { return <div className={`rounded-xl border p-4 ${tone === "emerald" ? "border-emerald-200 bg-emerald-50" : "bg-slate-50"}`}><div className="text-[9px] font-black uppercase tracking-wide text-slate-400">{label}</div><div className="mt-2 text-sm font-bold leading-6 text-slate-800">{show(value)}</div></div>; }
function ListPanel({ title, items }: { title: string; items: unknown }) { const values = strings(items); return <div className="rounded-xl border bg-slate-50 p-4"><h5 className="text-xs font-black text-slate-950">{title}</h5>{values.length ? <ul className="mt-3 space-y-2">{values.map((item) => <li key={item} className="flex gap-2 text-xs leading-5 text-slate-600"><span className="font-black text-violet-600">•</span><span>{item}</span></li>)}</ul> : <p className="mt-2 text-xs text-slate-400">Not established yet.</p>}</div>; }
function DetailList({ items, empty, tone }: { items: Record<string, unknown>[]; empty: string; tone: "emerald" | "rose" }) { return items.length ? <div className="mt-3 space-y-3">{items.map((item, index) => <div key={`${show(item.title)}-${index}`}><div className={`text-xs font-black ${tone === "emerald" ? "text-emerald-900" : "text-rose-900"}`}>{show(item.title)}</div><p className="mt-1 text-xs leading-5 text-slate-600">{show(item.detail)}</p></div>)}</div> : <p className="mt-3 text-xs text-slate-500">{empty}</p>; }
function Empty({ text }: { text: string }) { return <div className="rounded-xl border border-dashed bg-slate-50 p-4 text-sm leading-6 text-slate-500">{text}</div>; }
