import { Link } from 'react-router-dom';
import type { GrowthOverviewResponse } from '../types.js';
import { monitoringGuide } from '../growth-monitoring.js';
import { formatDisplayDate } from '@webtummy/core/display-date';
type Monitoring=GrowthOverviewResponse['growthIntelligence']['continuousMonitoring'];
export default function GrowthMonitoringPanel({monitoring,projectId}:{monitoring:Monitoring;projectId:string}){
 const rows=monitoring.sources.map(source=>({source,guide:monitoringGuide(source,projectId)}));
 const retained=monitoring.decision?.outcome.toLowerCase()==='retain';
 return <section className="space-y-4">
  <div className="rounded-xl border bg-white p-5"><h2 className="text-xl font-bold">Automatic growth checks</h2><p className="mt-2 max-w-3xl text-sm text-slate-600">These checks collect information that helps decide what to do next. They are separate from your execution tasks. Complete a missing setup when it is relevant to your plan; scheduled checks run in the background.</p>
   <div className="mt-4 grid gap-4 sm:grid-cols-3"><div className="text-sm"><span className="block text-xs text-slate-500">Last checked</span>{monitoring.lastCheckedAt?formatDisplayDate(monitoring.lastCheckedAt,{includeTime:true}):'No check recorded yet'}</div><div className="text-sm"><span className="block text-xs text-slate-500">Next automatic check</span>{monitoring.nextScheduledAt?formatDisplayDate(monitoring.nextScheduledAt,{includeTime:true}):'No check scheduled yet'}</div><div className="text-sm"><span className="block text-xs text-slate-500">Your next action</span>{retained?'Current action kept':monitoring.decision?'Latest decision recorded':'No decision recorded yet'}</div></div>
   {retained&&<p className="mt-3 rounded-lg bg-blue-50 p-3 text-sm text-blue-900">The last review kept your current action. Continue that task in Growth Execution.</p>}
   {monitoring.decision&&<details className="mt-3 text-xs text-slate-500"><summary className="cursor-pointer">Why the system made this decision</summary><p className="mt-2">{monitoring.decision.reason}</p></details>}
  </div>
  {[true,false].map(needsAction=><div key={String(needsAction)} className="rounded-xl border bg-white p-5"><h3 className="font-bold">{needsAction?'Needs setup or attention':'Scheduled and completed checks'}</h3><p className="mt-1 text-xs text-slate-500">{needsAction?'Missing data does not mean poor performance or restricted account access.':'You do not need to restart a check just because it is waiting.'}</p><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{rows.filter(row=>row.guide.needsAction===needsAction).map(({source,guide})=><div key={source.key} className="rounded-lg border p-4"><h4 className="text-sm font-semibold">{guide.title}</h4><span className={`mt-2 inline-block rounded-full px-2 py-1 text-xs ${needsAction?'bg-amber-50 text-amber-900':'bg-slate-100 text-slate-700'}`}>{guide.label}</span><p className="mt-3 text-sm text-slate-600">{guide.instruction}</p>{source.nextScheduledAt&&<p className="mt-2 text-xs text-slate-500">Next check: {formatDisplayDate(source.nextScheduledAt,{includeTime:true})}</p>}{guide.needsAction&&<Link to={guide.url} className="mt-3 inline-block rounded-lg bg-brand-600 px-3 py-2 text-xs font-semibold text-white">{guide.button} →</Link>}{source.restrictionReason&&<details className="mt-3 text-xs text-slate-500"><summary className="cursor-pointer">Saved check details</summary><p className="mt-2">{source.restrictionReason}</p></details>}</div>)}</div>{!rows.some(row=>row.guide.needsAction===needsAction)&&<p className="mt-3 text-sm text-slate-500">{needsAction?'No setup issues recorded.':'No checks recorded in this group yet.'}</p>}</div>)}
 </section>;
}
