import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../api.js';
type Item={id:string;title:string;recommendationReason:string;plannedPhase:string;plannedPublishAt:string|null;lifecycleStatus:string;executionTaskId:string|null;evidenceJson?:{socialCalendarPostId?:string;socialStrategyId?:string}};
type Post={id:string;strategyId:string};
export default function GrowthSocialPlan({projectId,taskId}:{projectId:string;taskId?:string|null}){
 const [items,setItems]=useState<Item[]>([]),[ready,setReady]=useState(false),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[month,setMonth]=useState(1);
 const [task,setTask]=useState<{title:string;manualInstructions:string}|null>(null),[platform,setPlatform]=useState(''),[withImage,setWithImage]=useState(true),[post,setPost]=useState<Post|null>(null);
 useEffect(()=>{let active=true;setLoaded(false);setTask(null);setPost(null);setError('');void api.get<{items:Item[];launchReady:boolean}>(`/api/projects-v2/${projectId}/growth/social-plan`).then(result=>{if(active){setItems(result.items);setReady(result.launchReady);setLoaded(true)}}).catch(e=>{if(active)setError(e.message)});
 if(taskId)void api.get<{task:{title:string;manualInstructions:string;projectId:string}}>(`/api/execution-tasks/${encodeURIComponent(taskId)}/execution-workspace`).then(result=>{if(active&&result.task.projectId===projectId)setTask(result.task)}).catch(e=>{if(active)setError(e.message)});
 return()=>{active=false};},[projectId,taskId]);
 const link=(saved:Post)=>`/social-strategy?projectId=${encodeURIComponent(projectId)}&campaignId=${encodeURIComponent(saved.strategyId)}&postId=${encodeURIComponent(saved.id)}&mode=posting`;
 async function start(item:Item){setBusy(true);setError('');try{await api.post(`/api/projects-v2/${projectId}/growth/content-roadmap/batches/approve`,{opportunityIds:[item.id],title:`Prepare social post: ${item.title}`.slice(0,220)});const result=await api.get<{items:Item[]}>(`/api/projects-v2/${projectId}/growth/social-plan`);const saved=result.items.find(row=>row.id===item.id);if(!saved?.executionTaskId)throw new Error('The task could not be found. Refresh and try again.');window.location.assign(`/social-strategy?projectId=${encodeURIComponent(projectId)}&growthTaskId=${encodeURIComponent(saved.executionTaskId)}`);}catch(e){setError(e instanceof Error?e.message:'Could not start this post.')}finally{setBusy(false)}}
 async function generate(){if(!task||!taskId||!platform)return;setBusy(true);setError('');try{const result=await api.post<{growthPost:Post}>(`/api/social-strategy/quick-post/generate`,{projectId,growthTaskId:taskId,platform,context:task.manualInstructions||task.title,generateImage:withImage});if(!result.growthPost)throw new Error('The social draft was not saved. Please try again.');setPost(result.growthPost);}catch(e){setError(e instanceof Error?e.message:'Could not prepare this post.')}finally{setBusy(false)}}
 const monthItems=items.filter(item=>{const day=Number(/^day_(\d+)$/.exec(item.plannedPhase)?.[1]);return day?Math.ceil(day/30)===month:month===1}).sort((a,b)=>Number(a.plannedPhase.replace('day_',''))-Number(b.plannedPhase.replace('day_','')));
 return <section className="order-2 rounded-xl border border-pink-200 bg-white p-5">
  <h2 className="text-lg font-bold text-slate-950">Your Growth social plan</h2><p className="mt-1 text-sm text-slate-600">At least four social suggestions each month for six months, shared with Growth → Content. Preparing a draft does not publish it.</p>
  {error&&<p role="alert" className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}
  {!loaded&&!error&&<p role="status" className="mt-3 text-sm">Loading your saved social plan…</p>}
  {loaded&&!ready&&<p className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Suggestions are ready to review. Publish and verify your website before starting social tasks.</p>}
  {taskId&&task&&<div className="mt-4 rounded-lg bg-pink-50 p-4"><h3 className="font-bold">{task.title}</h3><p className="mt-2 whitespace-pre-line text-xs leading-5 text-slate-600">{task.manualInstructions}</p>{post?<div role="status" className="mt-3"><p className="text-sm font-semibold text-emerald-800">Your draft is saved in the Social calendar and linked to Growth. Review it before approval.</p><Link to={link(post)} reloadDocument className="mt-3 inline-block rounded-lg bg-brand-600 px-4 py-2 text-sm font-bold text-white">Review saved social post</Link></div>:<div className="mt-3 flex flex-wrap items-center gap-3"><label className="text-sm">Platform<select value={platform} onChange={e=>setPlatform(e.target.value)} disabled={busy} className="ml-2 rounded-lg border p-2"><option value="">Choose platform</option><option value="facebook">Facebook</option><option value="instagram">Instagram</option></select></label><label className="text-sm"><input type="checkbox" checked={withImage} disabled={busy} onChange={e=>setWithImage(e.target.checked)}/> Prepare an image</label><button type="button" onClick={()=>void generate()} disabled={busy||!ready||!platform} className="rounded-lg bg-brand-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{busy?'Preparing and saving your draft…':'Prepare draft with AI'}</button></div>}</div>}
  {loaded&&<details className="mt-4" open={!taskId}><summary className="cursor-pointer text-sm font-bold">View planned social posts ({items.length})</summary><div className="mt-3 flex flex-wrap gap-2">{[1,2,3,4,5,6].map(value=><button type="button" key={value} onClick={()=>setMonth(value)} className={`rounded-lg border px-3 py-2 text-xs font-semibold ${month===value?'bg-pink-100 text-pink-900':'bg-white'}`}>Month {value}</button>)}</div><div className="mt-3 grid gap-3 md:grid-cols-2">{monthItems.map(item=><article key={item.id} className="rounded-lg border p-4"><div className="text-xs font-bold text-pink-700">Social media post · {item.lifecycleStatus.replaceAll('_',' ')} · {item.plannedPublishAt?new Date(item.plannedPublishAt).toLocaleDateString():item.plannedPhase.replace('day_','Day ')}</div><h3 className="mt-2 font-bold">{item.title}</h3><p className="mt-2 text-xs leading-5 text-slate-600">{item.recommendationReason}</p>{ready&&item.executionTaskId?<Link to={item.evidenceJson?.socialCalendarPostId && item.evidenceJson.socialStrategyId ? link({id:item.evidenceJson.socialCalendarPostId,strategyId:item.evidenceJson.socialStrategyId}) : `/social-strategy?projectId=${projectId}&growthTaskId=${item.executionTaskId}`} reloadDocument className="mt-3 inline-block text-sm font-bold text-brand-700">Continue social task →</Link>:ready&&['proposed','deferred'].includes(item.lifecycleStatus)&&<button type="button" disabled={busy} onClick={()=>void start(item)} className="mt-3 text-sm font-bold text-brand-700 disabled:opacity-50">Prepare this post →</button>}</article>)}</div>{!items.length&&<p className="mt-3 text-sm text-slate-600">Create the Growth content roadmap first. Its social suggestions will appear here.</p>}</details>}
 </section>;
}
