import {useEffect,useState} from 'react';
import {api} from '../api.js';
type Settings={enabled:boolean;siteKey:string;hostname:string;secretSaved:boolean;version:string};
export default function WebsiteRecaptchaSettings({projectId,onSaved}:{projectId:string;onSaved:()=>Promise<unknown>}){
 const [settings,setSettings]=useState<Settings|null>(null),[secret,setSecret]=useState(''),[showSecret,setShowSecret]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 useEffect(()=>{let active=true;api.get<Settings>(`/api/projects/${projectId}/website-builder/recaptcha`).then(data=>{if(active)setSettings(data)}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Could not load spam-protection settings.')});return()=>{active=false}},[projectId]);
 async function save(){if(!settings)return;setBusy(true);setError('');setMessage('');try{const result=await api.patch<Settings>(`/api/projects/${projectId}/website-builder/recaptcha`,{enabled:settings.enabled,siteKey:settings.siteKey,hostname:settings.hostname,...(secret.trim()?{secretKey:secret.trim()}:{})});setSettings(result);setSecret('');setShowSecret(false);await onSaved();setMessage('Saved. Review and approve the updated website, then export or publish it to apply this setting.');}catch(e){setError(e instanceof Error?e.message:'Could not save reCAPTCHA.')}finally{setBusy(false)}}
 return <details className="group mt-5 rounded-xl border border-slate-200 bg-white"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 p-4 [&::-webkit-details-marker]:hidden"><div><span className="block text-sm font-bold text-slate-900">Form spam protection · reCAPTCHA</span><span className="mt-1 block text-xs text-slate-500">{settings?.enabled?'Configured for the next approved website version':'Optional · protect your enquiry forms'}</span></div><span className="text-xs font-bold text-indigo-700"><span className="group-open:hidden">Expand +</span><span className="hidden group-open:inline">Collapse −</span></span></summary><div className="space-y-4 border-t p-4">
 <p className="text-sm text-slate-600">Add Google’s “I’m not a robot” checkbox to SEnuke-managed enquiry forms. You will need a Google account and a reCAPTCHA v2 site key and secret key.</p>
 <ol className="list-decimal space-y-2 pl-5 text-sm text-slate-600"><li><a href="https://www.google.com/recaptcha/admin/create" target="_blank" rel="noopener noreferrer" className="font-semibold text-indigo-700 underline">Open Google reCAPTCHA registration ↗</a> and sign in or create a Google account.</li><li>Register your website, choose <b>reCAPTCHA v2 → “I’m not a robot” Checkbox</b>, and add the live domain, such as example.com, without https:// or a page path.</li><li>Copy the site key and secret key into the fields below. If Google shows a Cloud key, use its compatible legacy secret key. <a href="https://docs.cloud.google.com/recaptcha/docs/create-key-website#find-key" target="_blank" rel="noopener noreferrer" className="text-indigo-700 underline">Google’s key instructions ↗</a></li><li>Enable protection, save, then review and publish the updated website. Test the form on the registered domain.</li></ol>
 {error&&<p role="alert" className="rounded-lg bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}
 {settings?<form onSubmit={e=>{e.preventDefault();void save()}} className="space-y-4"><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={settings.enabled} onChange={e=>setSettings({...settings,enabled:e.target.checked})}/>Enable reCAPTCHA on generated enquiry forms</label><label className="block text-xs font-bold text-slate-700">Registered website domain<input required value={settings.hostname} onChange={e=>setSettings({...settings,hostname:e.target.value})} placeholder="example.com" autoComplete="off" className="mt-1 block w-full rounded-lg border p-2.5 text-sm font-normal"/></label><label className="block text-xs font-bold text-slate-700">Site key (public)<input required={settings.enabled} value={settings.siteKey} onChange={e=>setSettings({...settings,siteKey:e.target.value})} maxLength={255} autoComplete="off" spellCheck={false} className="mt-1 block w-full rounded-lg border p-2.5 text-sm font-normal"/></label><div><label htmlFor="website-recaptcha-secret" className="block text-xs font-bold text-slate-700">Secret key (private)</label><div className="mt-1 flex gap-2"><input id="website-recaptcha-secret" type={showSecret?'text':'password'} required={settings.enabled&&!settings.secretSaved} value={secret} onChange={e=>setSecret(e.target.value)} placeholder={settings.secretSaved?'Secret saved securely — leave blank to keep it':'Paste the secret key'} maxLength={500} autoComplete="new-password" spellCheck={false} className="min-w-0 flex-1 rounded-lg border p-2.5 text-sm"/><button type="button" onClick={()=>setShowSecret(!showSecret)} aria-pressed={showSecret} className="rounded-lg border px-3 text-xs font-semibold">{showSecret?'Hide':'Show'}</button></div><p className="mt-2 text-xs text-slate-500">The secret is encrypted and is not included in page HTML, JavaScript, AI prompts or downloads. For downloaded PHP websites, your developer must also set SENUKE_RECAPTCHA_SECRET on the hosting server; see CONTACT-FORM-SETUP.md in the ZIP. WordPress plugin forms and custom form endpoints need reCAPTCHA configured in their own handler.</p></div><button disabled={busy} className="rounded-lg bg-indigo-700 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{busy?'Saving…':'Save reCAPTCHA settings'}</button>{message&&<p role="status" className="text-sm text-emerald-800">{message}</p>}</form>:!error&&<p className="text-sm text-slate-500">Loading settings…</p>}
 </div></details>;
}
