import {useState} from 'react';
import {ResponsiveContainer,AreaChart,Area,XAxis,YAxis,CartesianGrid,Tooltip,Legend} from 'recharts';
import type {websiteAnalytics} from '../../../api/src/website-analytics.js';
export type WebsiteAnalyticsData=ReturnType<typeof websiteAnalytics>;
export default function WebsiteAnalyticsDashboard({data,available}:{data:WebsiteAnalyticsData;available:boolean}){
 const [pageSort,setPageSort]=useState<'views'|'successes'>('views'),[allPages,setAllPages]=useState(false),[journey,setJourney]=useState<'common'|'converted'>('common');
 if(!available&&!data.eventCount)return <section className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h3 className="font-bold">Website tracking not available</h3><p className="mt-2 text-sm text-slate-600">Connect and verify the tracking tag to see visitor activity, popular pages and form results.</p></section>;
 const pages=[...data.topPages].sort((a,b)=>b[pageSort]-a[pageSort]);const paths=journey==='common'?data.commonPaths:data.convertingPaths;
 const successes=data.forms.reduce((n,f)=>n+f.successes,0),attempts=data.forms.reduce((n,f)=>n+f.attempts,0),errors=data.forms.reduce((n,f)=>n+f.errors,0);
 const conversion=data.sessions?`${(100*data.convertedSessions/data.sessions).toFixed(1)}%`:'—';
 return <div className="space-y-5">
 {data.limited&&<p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">This report covers the latest 10,000 recorded events in this date range. Totals and paths may be incomplete. Choose a shorter date range for a more complete view.</p>}
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['Tracked visits',data.sessions,'Visits are sessions, not unique people.'],['Recorded form successes',successes,'Success events reported by your website.'],['Visits with a form success',conversion,`${data.convertedSessions} of ${data.sessions} tracked visits`],['Form errors',errors,'Recorded errors, not inferred failed enquiries.']].map(([label,value,note])=><div key={String(label)} className="rounded-xl border bg-white p-4"><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold text-slate-950">{value}</p><p className="mt-2 text-xs text-slate-500">{note}</p></div>)}</div>
 <section className="rounded-2xl border bg-white p-5"><h3 className="font-bold text-slate-950">Visits and enquiries over time</h3><p className="mt-1 text-xs text-slate-500">Daily totals in UTC. Every recorded visit is included, even on low-traffic days.</p><div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.daily} margin={{top:10,right:12,left:0,bottom:0}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tickFormatter={v=>String(v).slice(5)} minTickGap={35}/><YAxis allowDecimals={false}/><Tooltip/><Legend/><Area type="linear" dataKey="views" name="Page views" stroke="#0891b2" fill="#cffafe" fillOpacity={.6}/><Area type="linear" dataKey="sessions" name="Tracked visits" stroke="#4f46e5" fill="#e0e7ff" fillOpacity={.3}/><Area type="linear" dataKey="successes" name="Form successes" stroke="#059669" fill="#d1fae5" fillOpacity={.3}/></AreaChart></ResponsiveContainer></div>{!data.eventCount&&<p className="mt-2 text-sm text-slate-500">No activity was recorded in this date range.</p>}</section>
 <div className="grid gap-5 xl:grid-cols-2"><section className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-bold">Top pages</h3><p className="mt-1 text-xs text-slate-500">Rank by visits or recorded form successes. No minimum traffic required.</p></div><select aria-label="Rank pages by" value={pageSort} onChange={e=>setPageSort(e.target.value as 'views'|'successes')} className="rounded-lg border px-3 py-2 text-sm"><option value="views">Most viewed</option><option value="successes">Most form successes</option></select></div><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-xs text-slate-500"><tr><th className="pb-3">Page</th><th className="p-2 text-right">Views</th><th className="p-2 text-right">Visits</th><th className="p-2 text-right">Successes</th></tr></thead><tbody>{pages.slice(0,allPages?undefined:10).map(p=><tr key={p.path} className="border-b"><td className="max-w-xs break-all py-3 pr-3">{p.path}<div className="mt-2 h-1 rounded bg-slate-100"><div className="h-1 rounded bg-cyan-500" style={{width:`${pages[0]?.[pageSort]?100*p[pageSort]/pages[0][pageSort]:0}%`}}/></div></td><td className="p-2 text-right">{p.views}</td><td className="p-2 text-right">{p.sessions}</td><td className="p-2 text-right">{p.successes}</td></tr>)}</tbody></table></div>{!pages.length&&<p className="mt-3 text-sm text-slate-500">No pages recorded yet.</p>}{pages.length>10&&<button onClick={()=>setAllPages(!allPages)} className="mt-3 text-sm font-semibold text-brand-700">{allPages?'Show top 10':`Show all ${pages.length} pages`}</button>}</section>
 <section className="rounded-2xl border bg-white p-5"><h3 className="font-bold">Where visits came from</h3><p className="mt-1 text-xs text-slate-500">Referring website recorded at the start of each tracked visit. Unknown sources stay unknown.</p><div className="mt-4 space-y-3">{data.sources.map(s=><div key={s.source}><div className="flex justify-between gap-3 text-sm"><span className="break-all">{s.source}</span><b>{s.sessions} visits</b></div><div className="mt-2 h-2 rounded bg-slate-100"><div className="h-2 rounded bg-indigo-500" style={{width:`${data.sessions?100*s.sessions/data.sessions:0}%`}}/></div><p className="mt-1 text-xs text-slate-500">{s.convertedSessions} visits with a form success</p></div>)}{!data.sources.length&&<p className="text-sm text-slate-500">No visit sources recorded yet.</p>}</div></section></div>
 <section className="rounded-2xl border bg-white p-5"><h3 className="font-bold">Contact forms and enquiries</h3><p className="mt-2 max-w-4xl text-sm text-slate-600">A form submission is an attempt. A success means your website reported a successful submission; it does not confirm delivery to your inbox or CRM. This includes all tracked forms, identified by page and form name.</p>{attempts>0&&successes===0&&<p className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Submission attempts are recorded, but no success events were received. Check both the form and its success tracking before concluding that enquiries failed.</p>}<div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-xs text-slate-500"><tr><th className="pb-3">Page / form</th>{['Started','Submitted','Success','Errors'].map(t=><th key={t} className="p-2 text-right">{t}</th>)}</tr></thead><tbody>{data.forms.map(f=><tr key={`${f.path}:${f.form}`} className="border-b"><td className="py-3 pr-3"><span className="break-all">{f.path}</span><span className="mt-1 block text-xs text-slate-500">{f.form}</span></td>{[f.starts,f.attempts,f.successes,f.errors].map((v,i)=><td key={i} className="p-2 text-right">{v}</td>)}</tr>)}</tbody></table></div>{!data.forms.length&&<p className="mt-3 text-sm text-slate-500">No form activity recorded. Check that the form emits start, submit, success and error events.</p>}</section>
 <section className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold">Visitor paths</h3><p className="mt-1 text-xs text-slate-500">Observed paths within this date range. Popular does not necessarily mean effective.</p></div><select aria-label="Visitor path ranking" value={journey} onChange={e=>setJourney(e.target.value as 'common'|'converted')} className="rounded-lg border px-3 py-2 text-sm"><option value="common">Most common paths</option><option value="converted">Paths to a form success</option></select></div><div className="mt-4 space-y-3">{paths.map((p,i)=><div key={i} className="rounded-xl border bg-slate-50 p-4"><div className="flex flex-wrap items-center gap-2 text-xs">{p.pages.map((page,j)=><span key={j} className="contents">{j>0&&<span aria-hidden="true" className="text-slate-400">→</span>}<span className="max-w-full break-all rounded-lg border bg-white px-3 py-2 font-semibold">{page}</span></span>)}{p.truncated&&<span>→ more pages</span>}</div><p className="mt-3 text-xs text-slate-600">{p.sessions} tracked visits · {p.convertedSessions} with a form success</p></div>)}{!paths.length&&<p className="rounded-lg bg-slate-50 p-4 text-sm text-slate-500">{journey==='converted'?'No paths with a recorded form success yet.':'No visitor paths recorded yet.'}</p>}</div>{data.missingSessionEvents>0&&<p className="mt-3 text-xs text-slate-500">{data.missingSessionEvents} events lack a session identifier and cannot be assigned to a visitor path.</p>}</section>
 </div>;
}
