<?php
/**
 * Plugin Name: SENuke AI Connector
 * Description: Secure WordPress deployment bridge for complete SENuke AI website releases: pages/posts, media, SEO/schema, menus, forms, managed runtime theme, backups and rollback.
 * Version: 1.5.5
 * Author: SENuke AI
 */
if (!defined('ABSPATH')) exit;

final class SENuke_AI_Connector {
    const NS='senuke/v1';
    const FORM_OPTION='senuke_ai_forms';
    const STYLE_OPTION='senuke_ai_design_package';
    const STYLE_RELEASES_OPTION='senuke_ai_release_design_packages';
    const BACKUP_OPTION='senuke_ai_deployment_backups';
    const IDENTITY_OPTION='senuke_ai_site_identity';
    const IDENTITY_RELEASES_OPTION='senuke_ai_release_identities';
    const MENU_OPTION='senuke_ai_navigation_menus';
    const THEME_STYLESHEET='senuke-theme';
    const VERSION='1.5.5';

    public static function boot(){add_action('init',[__CLASS__,'register_blocks']);add_action('init',[__CLASS__,'register_seo_meta']);add_action('enqueue_block_editor_assets',[__CLASS__,'enqueue_editor_assets']);add_filter('block_categories_all',[__CLASS__,'block_categories'],10,2);add_action('rest_api_init',[__CLASS__,'routes']);add_action('add_meta_boxes',[__CLASS__,'add_seo_meta_boxes']);add_action('save_post',[__CLASS__,'save_seo_meta_box']);add_action('wp_head',[__CLASS__,'head_meta'],2);add_action('wp_enqueue_scripts',[__CLASS__,'enqueue_design_package'],30);add_action('template_redirect',[__CLASS__,'render_release_page'],1);add_filter('pre_get_document_title',[__CLASS__,'document_title'],99);add_filter('wp_robots',[__CLASS__,'robots_directives'],99);add_shortcode('senuke_form',[__CLASS__,'form_shortcode']);add_shortcode('senuke_identity',[__CLASS__,'identity_shortcode']);add_shortcode('senuke_footer_legal',[__CLASS__,'footer_legal_shortcode']);add_action('admin_post_senuke_form_submit',[__CLASS__,'form_submit']);add_action('admin_post_nopriv_senuke_form_submit',[__CLASS__,'form_submit']);}
    public static function block_categories($categories,$context){foreach($categories as $category)if(($category['slug']??'')==='senuke-sections')return $categories;array_unshift($categories,['slug'=>'senuke-sections','title'=>'SENuke Sections','icon'=>'layout']);return $categories;}
    public static function register_blocks(){
        wp_register_script('senuke-ai-blocks',plugins_url('senuke-blocks.js',__FILE__),['wp-blocks','wp-element','wp-block-editor','wp-components','wp-i18n','wp-rich-text','wp-data','wp-plugins','wp-edit-post','wp-editor'],self::VERSION,true);
        wp_register_style('senuke-ai-blocks-editor',plugins_url('senuke-blocks.css',__FILE__),[],self::VERSION);
        $blocks=['header','navigation','section-layout','local-service-hero','rich-text','image','service-grid','benefits','process','proof','faq','cta','contact-form','footer'];
        $attributes=['componentId'=>['type'=>'string'],'instanceId'=>['type'=>'string'],'componentVersion'=>['type'=>'string','default'=>'1.0.0'],'variant'=>['type'=>'string','default'=>'standard'],'props'=>['type'=>'object','default'=>[]],'lock'=>['type'=>'object'],'align'=>['type'=>'string'],'style'=>['type'=>'object'],'backgroundColor'=>['type'=>'string'],'textColor'=>['type'=>'string'],'gradient'=>['type'=>'string'],'fontSize'=>['type'=>'string']];
        $supports=['html'=>false,'reusable'=>true,'lock'=>true,'anchor'=>true,'align'=>['wide','full'],'color'=>['background'=>true,'text'=>true,'gradients'=>true],'spacing'=>['padding'=>true,'margin'=>true,'blockGap'=>true],'typography'=>['fontSize'=>true,'lineHeight'=>true],'border'=>['color'=>true,'radius'=>true,'style'=>true,'width'=>true]];
        foreach($blocks as $name)register_block_type('senuke/'.$name,['api_version'=>2,'editor_script'=>'senuke-ai-blocks','style'=>'senuke-ai-blocks-editor','editor_style'=>'senuke-ai-blocks-editor','render_callback'=>[__CLASS__,'render_component_block'],'attributes'=>$attributes,'supports'=>$supports]);
        self::register_block_patterns();
    }
    public static function enqueue_editor_assets(){wp_enqueue_script('senuke-ai-blocks');wp_enqueue_style('senuke-ai-blocks-editor');}
    public static function register_seo_meta(){
        $definitions=[
            '_senuke_meta_title'=>['type'=>'string','sanitize_callback'=>'sanitize_text_field'],
            '_senuke_meta_description'=>['type'=>'string','sanitize_callback'=>'sanitize_textarea_field'],
            '_senuke_canonical_url'=>['type'=>'string','sanitize_callback'=>'esc_url_raw'],
            '_senuke_robots'=>['type'=>'string','sanitize_callback'=>'sanitize_text_field'],
            '_senuke_schema_json'=>['type'=>'string','sanitize_callback'=>[__CLASS__,'sanitize_schema_meta']],
        ];
        foreach(['page','post'] as $post_type)foreach($definitions as $key=>$args)register_post_meta($post_type,$key,array_merge($args,['single'=>true,'show_in_rest'=>true,'auth_callback'=>fn()=>current_user_can('edit_posts')]));
    }
    public static function sanitize_schema_meta($value){$value=is_string($value)?wp_unslash($value):'';if(trim($value)==='')return'';$decoded=json_decode($value,true);return json_last_error()===JSON_ERROR_NONE?wp_json_encode($decoded):'';}
    public static function add_seo_meta_boxes(){foreach(['page','post'] as $post_type)add_meta_box('senuke-page-seo','SENuke Page SEO',[__CLASS__,'render_seo_meta_box'],$post_type,'normal','high');}
    public static function render_seo_meta_box($post){
        wp_nonce_field('senuke_save_page_seo','senuke_page_seo_nonce');
        $title=(string)get_post_meta($post->ID,'_senuke_meta_title',true);$description=(string)get_post_meta($post->ID,'_senuke_meta_description',true);$canonical=(string)get_post_meta($post->ID,'_senuke_canonical_url',true);$robots=(string)get_post_meta($post->ID,'_senuke_robots',true)?:'index, follow';$schema=(string)get_post_meta($post->ID,'_senuke_schema_json',true);
        $discouraged=(string)get_option('blog_public','1')==='0';
        echo'<div class="senuke-seo-fields">';if($discouraged)echo'<p style="border:1px solid #d63638;background:#fcf0f1;padding:10px 12px"><strong>Search visibility is disabled for this WordPress site.</strong> Published pages will output noindex until Settings → Reading → “Discourage search engines” is turned off.</p>';
        echo'<p><label><strong>SEO title</strong><br><input class="widefat" type="text" maxlength="70" name="senuke_meta_title" value="'.esc_attr($title).'"></label></p>';
        echo'<p><label><strong>Meta description</strong><br><textarea class="widefat" rows="3" maxlength="170" name="senuke_meta_description">'.esc_textarea($description).'</textarea></label></p>';
        echo'<p><label><strong>Canonical URL</strong><br><input class="widefat" type="url" name="senuke_canonical_url" value="'.esc_attr($canonical).'" placeholder="'.esc_attr(get_permalink($post)).'"></label></p>';
        echo'<p><label><strong>Search engine access</strong><br><select name="senuke_robots"><option value="index, follow"'.selected($robots,'index, follow',false).'>Index and follow</option><option value="noindex, follow"'.selected($robots,'noindex, follow',false).'>Do not index; follow links</option><option value="noindex, nofollow"'.selected($robots,'noindex, nofollow',false).'>Do not index or follow</option></select></label></p>';
        echo'<p><label><strong>Schema JSON-LD</strong><br><textarea class="widefat code" rows="8" name="senuke_schema_json">'.esc_textarea($schema).'</textarea></label><br><small>Use valid JSON. Invalid schema is not saved.</small></p></div>';
    }
    public static function save_seo_meta_box($post_id){
        if(!isset($_POST['senuke_page_seo_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['senuke_page_seo_nonce'])),'senuke_save_page_seo')||defined('DOING_AUTOSAVE')&&DOING_AUTOSAVE||!current_user_can('edit_post',$post_id))return;
        $post_type=get_post_type($post_id);if(!in_array($post_type,['page','post'],true))return;
        $canonical=esc_url_raw(wp_unslash($_POST['senuke_canonical_url']??''));if($canonical&&strpos($canonical,'/')===0)$canonical=home_url($canonical);
        $fields=['_senuke_meta_title'=>sanitize_text_field(wp_unslash($_POST['senuke_meta_title']??'')),'_senuke_meta_description'=>sanitize_textarea_field(wp_unslash($_POST['senuke_meta_description']??'')),'_senuke_canonical_url'=>$canonical,'_senuke_robots'=>sanitize_text_field(wp_unslash($_POST['senuke_robots']??'index, follow')),'_senuke_schema_json'=>self::sanitize_schema_meta($_POST['senuke_schema_json']??'')];
        foreach($fields as $key=>$value){if($value==='')delete_post_meta($post_id,$key);else update_post_meta($post_id,$key,$value);}
    }
    private static function pattern_block($name,$component_id,$props,$variant='standard'){$attributes=['componentId'=>$component_id,'instanceId'=>'senuke-manual-'.wp_generate_uuid4(),'componentVersion'=>'1.0.0','variant'=>$variant,'props'=>$props];return'<!-- wp:senuke/'.$name.' '.wp_json_encode($attributes).' /-->';}
    private static function register_block_patterns(){
        if(!function_exists('register_block_pattern'))return;
        if(function_exists('register_block_pattern_category'))register_block_pattern_category('senuke-sections',['label'=>'SENuke Sections']);
        $patterns=[
            'hero'=>['Hero','local-service-hero','hero.local_service',['eyebrow'=>'Welcome','headline'=>'Add a clear customer-focused headline','summary'=>'Explain the value of this page and the next step.','primaryCtaLabel'=>'Get started','primaryCtaUrl'=>'#contact'],'split'],
            'introduction'=>['Introduction','rich-text','content.rich_text',['heading'=>'Introduce this topic','body'=>'Add useful, audience-focused information here.'],'standard'],
            'services'=>['Services Grid','service-grid','service.grid',['heading'=>'How we can help','introduction'=>'Choose the services most relevant to this page.','items'=>[['title'=>'Service one','description'=>'Explain the outcome this service provides.','url'=>'#'],['title'=>'Service two','description'=>'Explain the outcome this service provides.','url'=>'#'],['title'=>'Service three','description'=>'Explain the outcome this service provides.','url'=>'#']]],'cards'],
            'benefits'=>['Benefits','benefits','service.benefits',['heading'=>'Why choose us','items'=>[['title'=>'Clear benefit','description'=>'Add supporting detail.'],['title'=>'Trusted experience','description'=>'Add supporting detail.'],['title'=>'Helpful next step','description'=>'Add supporting detail.']]],'cards'],
            'process'=>['Process','process','content.process',['heading'=>'How it works','steps'=>[['title'=>'Start','description'=>'Describe the first step.'],['title'=>'Plan','description'=>'Describe the second step.'],['title'=>'Complete','description'=>'Describe the outcome.']]],'numbered'],
            'proof'=>['Trust & Proof','proof','trust.proof',['heading'=>'Why customers trust us','introduction'=>'Use verified facts and approved proof only.','items'=>[['title'=>'Evidence','description'=>'Add a verified trust signal.'],['title'=>'Experience','description'=>'Add a verified trust signal.']]],'cards'],
            'faq'=>['FAQ','faq','content.faq',['heading'=>'Frequently asked questions','items'=>[['question'=>'Add a customer question','answer'=>'Add a useful, factual answer.'],['question'=>'Add another question','answer'=>'Add a useful, factual answer.']]],'accordion'],
            'cta'=>['Call to Action','cta','conversion.cta',['heading'=>'Ready to take the next step?','body'=>'Explain what happens after the customer responds.','buttonLabel'=>'Contact us','buttonUrl'=>'#contact'],'band'],
            'contact'=>['Contact Form','contact-form','conversion.contact_form',['heading'=>'Contact us','introduction'=>'Tell customers how the team will respond.','submitLabel'=>'Send enquiry','successMessage'=>'Thank you. Your enquiry has been received.'],'standard'],
        ];
        foreach($patterns as $slug=>$pattern)register_block_pattern('senuke/'.$slug,['title'=>$pattern[0],'categories'=>['senuke-sections'],'blockTypes'=>['senuke/'.$pattern[1]],'inserter'=>true,'content'=>self::pattern_block($pattern[1],$pattern[2],$pattern[3],$pattern[4])]);
    }
    private static function block_value($props,$key,$fallback=''){return isset($props[$key])&&is_scalar($props[$key])?(string)$props[$key]:$fallback;}
    private static function block_rich($props,$key,$fallback=''){return wp_kses_post(self::block_value($props,$key,$fallback));}
    private static function block_items($props,$key){return isset($props[$key])&&is_array($props[$key])?$props[$key]:[];}
    private static function block_alignment($props){$alignment=sanitize_key(self::block_value($props,'alignment','left'));return in_array($alignment,['left','center','right'],true)?' senuke-align-'.$alignment:'';}
    private static function block_button($label,$url){$label=trim((string)$label);if($label==='')return'';return'<a class="senuke-button" href="'.esc_url($url?:'#').'">'.esc_html($label).'</a>';}
    private static function block_cards($items,$extra=''){if(!$items)return'';$html='<div class="senuke-grid">';foreach($items as $item){if(!is_array($item))continue;$title=self::block_value($item,'title',self::block_value($item,'name'));$body=self::block_value($item,'description',self::block_value($item,'body',self::block_value($item,'text')));$url=self::block_value($item,'url');$html.='<article class="senuke-card '.$extra.'">'.($title?'<h3>'.wp_kses_post($title).'</h3>':'').($body?wp_kses_post(wpautop($body)):'').($url?'<a href="'.esc_url($url).'">Learn more</a>':'').'</article>';}$html.='</div>';return$html;}
    private static function render_nested_component($component){if(!is_array($component))return'';return self::render_component_block(['componentId'=>sanitize_text_field($component['componentId']??''),'instanceId'=>sanitize_text_field($component['instanceId']??''),'componentVersion'=>sanitize_text_field($component['componentVersion']??'1.0.0'),'variant'=>sanitize_key($component['variant']??'standard'),'props'=>is_array($component['props']??null)?$component['props']:[]],'',null);}
    public static function render_component_block($attributes,$content='',$block=null){
        $id=sanitize_text_field($attributes['componentId']??'');
        $variant=sanitize_key($attributes['variant']??'standard');
        $props=is_array($attributes['props']??null)?$attributes['props']:[];
        $second=!empty($props['isSecondFold'])?' senuke-second-fold':'';
        $alignment=$second.self::block_alignment($props);
        $heading=self::block_value($props,'heading');
        $wrap=static function($html){$wrapper=get_block_wrapper_attributes(['class'=>'senuke-gutenberg-block']);return'<div '.$wrapper.'>'.$html.'</div>';};
        switch($id){
            case'layout.section':
                $layout=in_array($variant,['one_column','two_equal','two_left_wide','two_right_wide','three_equal'],true)?$variant:'two_equal';
                $columns=trim((string)$content);
                if($columns===''){$slots=$layout==='one_column'?['columnOne']:($layout==='three_equal'?['columnOne','columnTwo','columnThree']:['columnOne','columnTwo']);$columns='';foreach($slots as $index=>$slot){$children='';foreach(self::block_items($props,$slot)as$child)$children.=self::render_nested_component($child);$columns.='<div class="senuke-layout-column" data-column="'.($index+1).'">'.$children.'</div>';}}
                $background=sanitize_key(self::block_value($props,'backgroundColor','default'));$text=sanitize_key(self::block_value($props,'textColor','auto'));$spacing=sanitize_key(self::block_value($props,'spacing','comfortable'));$image=esc_url(self::block_value($props,'backgroundImageUrl'));$media=$image?'<img class="senuke-layout-background-image" src="'.$image.'" alt="" aria-hidden="true">':'';
                return$wrap('<section class="senuke-component senuke-layout-section'.$second.' senuke-layout-'.$layout.' senuke-layout-bg-'.$background.' senuke-layout-text-'.$text.' senuke-layout-spacing-'.$spacing.'">'.$media.'<div class="senuke-layout-columns">'.$columns.'</div></section>');
            case'hero.local_service':$image=esc_url(self::block_value($props,'imageUrl'));$media=$image?'<img class="senuke-hero-image" src="'.$image.'" alt="'.esc_attr(wp_strip_all_tags(self::block_value($props,'imageAltText',self::block_value($props,'headline')))).'">':'';return$wrap('<section class="senuke-component senuke-hero senuke-'.$variant.$alignment.'"><div>'.(self::block_value($props,'eyebrow')?'<p class="senuke-eyebrow">'.self::block_rich($props,'eyebrow').'</p>':'').'<h1>'.self::block_rich($props,'headline').'</h1><div class="senuke-lead">'.wp_kses_post(wpautop(self::block_value($props,'summary'))).'</div>'.self::block_button(self::block_value($props,'primaryCtaLabel'),self::block_value($props,'primaryCtaUrl')).'</div>'.$media.'</section>');
            case'content.rich_text':return$wrap('<section class="senuke-component senuke-rich-text'.$alignment.'"><h2>'.wp_kses_post($heading).'</h2>'.wp_kses_post(wpautop(self::block_value($props,'body'))).'</section>');
            case'media.image':$image=esc_url(self::block_value($props,'imageUrl'));return$wrap('<figure class="senuke-component senuke-media'.$second.' senuke-media-'.$variant.'">'.($image?'<img src="'.$image.'" alt="'.esc_attr(self::block_value($props,'imageAltText',self::block_value($props,'altText'))).'">':'').(self::block_value($props,'caption')?'<figcaption>'.esc_html(self::block_value($props,'caption')).'</figcaption>':'').'</figure>');
            case'service.grid':return$wrap('<section class="senuke-component senuke-services senuke-services-'.$variant.$alignment.'"><h2>'.wp_kses_post($heading).'</h2>'.(self::block_value($props,'introduction')?wp_kses_post(wpautop(self::block_value($props,'introduction'))):'').self::block_cards(self::block_items($props,'items')).'</section>');
            case'service.benefits':return$wrap('<section class="senuke-component senuke-benefits senuke-benefits-'.$variant.$alignment.'"><h2>'.wp_kses_post($heading).'</h2>'.self::block_cards(self::block_items($props,'items'),'senuke-benefit').'</section>');
            case'content.process':$steps='<ol class="senuke-steps">';foreach(self::block_items($props,'steps')as$item){if(!is_array($item))continue;$steps.='<li><h3>'.wp_kses_post(self::block_value($item,'title',self::block_value($item,'name'))).'</h3>'.wp_kses_post(wpautop(self::block_value($item,'description',self::block_value($item,'body')))).'</li>';}$steps.='</ol>';return$wrap('<section class="senuke-component senuke-process senuke-process-'.$variant.$alignment.'"><h2>'.wp_kses_post($heading).'</h2>'.$steps.'</section>');
            case'trust.proof':return$wrap('<section class="senuke-component senuke-proof'.$alignment.'"><h2>'.wp_kses_post($heading).'</h2>'.(self::block_value($props,'introduction')?wp_kses_post(wpautop(self::block_value($props,'introduction'))):'').self::block_cards(self::block_items($props,'items')).'</section>');
            case'content.faq':$faqs='';foreach(self::block_items($props,'items')as$item){if(!is_array($item))continue;$faqs.='<details><summary>'.wp_kses_post(self::block_value($item,'question',self::block_value($item,'title'))).'</summary>'.wp_kses_post(wpautop(self::block_value($item,'answer',self::block_value($item,'description')))).'</details>';}return$wrap('<section class="senuke-component senuke-faq'.$alignment.'"><h2>'.wp_kses_post($heading).'</h2>'.$faqs.'</section>');
            case'conversion.cta':return$wrap('<section class="senuke-component senuke-cta'.$alignment.'"><h2>'.wp_kses_post($heading).'</h2>'.wp_kses_post(wpautop(self::block_value($props,'body'))).self::block_button(self::block_value($props,'buttonLabel'),self::block_value($props,'buttonUrl')).'</section>');
            case'conversion.contact_form':$shortcode=self::block_value($props,'formShortcode');$form=$shortcode?do_shortcode($shortcode):'<p class="senuke-form-placeholder">Connect the approved SENuke form before publishing.</p>';return$wrap('<section class="senuke-component senuke-contact-form senuke-contact-form-shortcode'.$alignment.'"><div><h2>'.wp_kses_post($heading).'</h2>'.wp_kses_post(wpautop(self::block_value($props,'introduction'))).'</div><div>'.$form.'</div></section>');
            case'global.navigation':
                $location=sanitize_key(self::block_value($props,'location','primary'));if(!in_array($location,['primary','footer'],true))$location='primary';$name=$location==='footer'?'SENuke Footer Navigation':'SENuke Primary Navigation';$class=$location==='footer'?'senuke-footer-navigation':'senuke-primary-nav';$menu=self::release_menu($name,$class,$location);if(!$menu)return'';if($location==='footer')return$menu;$mobile=self::release_menu($name,$class.' senuke-primary-nav-mobile',$location);return'<div class="senuke-managed-navigation"><div class="senuke-header-navigation">'.$menu.'</div><details class="senuke-mobile-menu"><summary aria-label="Open navigation menu"><span class="senuke-menu-icon" aria-hidden="true"><i></i><i></i><i></i></span><span class="senuke-visually-hidden">Menu</span></summary><div class="senuke-mobile-menu-panel">'.$mobile.'</div></details></div>';
            case'global.header':return$wrap('<header class="senuke-component senuke-header"><strong>'.esc_html(self::block_value($props,'businessName')).'</strong>'.self::block_button(self::block_value($props,'primaryCtaLabel'),self::block_value($props,'primaryCtaUrl')).'</header>');
            case'global.footer':return$wrap('<footer class="senuke-component senuke-footer"><strong>'.esc_html(self::block_value($props,'businessName')).'</strong>'.(self::block_value($props,'summary')?'<p>'.esc_html(self::block_value($props,'summary')).'</p>':'').'</footer>');
        }
        return$content;
    }
    public static function routes(){
        register_rest_route(self::NS,'/capabilities',['methods'=>'GET','permission_callback'=>fn()=>current_user_can('edit_pages'),'callback'=>[__CLASS__,'capabilities']]);
        register_rest_route(self::NS,'/pages/(?P<id>\d+)/optimize',['methods'=>'POST','permission_callback'=>fn($r)=>current_user_can('edit_post',(int)$r['id']),'callback'=>[__CLASS__,'optimize_page']]);
        register_rest_route(self::NS,'/menus',['methods'=>'POST','permission_callback'=>fn()=>current_user_can('edit_theme_options'),'callback'=>[__CLASS__,'create_menu']]);
        register_rest_route(self::NS,'/forms',['methods'=>'POST','permission_callback'=>fn()=>current_user_can('edit_pages'),'callback'=>[__CLASS__,'save_form']]);
        register_rest_route(self::NS,'/backups',['methods'=>'POST','permission_callback'=>fn()=>current_user_can('manage_options'),'callback'=>[__CLASS__,'create_backup']]);
        register_rest_route(self::NS,'/backups/(?P<id>[a-zA-Z0-9_-]+)/restore',['methods'=>'POST','permission_callback'=>fn()=>current_user_can('manage_options'),'callback'=>[__CLASS__,'restore_backup']]);
        register_rest_route(self::NS,'/site-package',['methods'=>'POST','permission_callback'=>fn()=>current_user_can('edit_theme_options'),'callback'=>[__CLASS__,'save_design_package']]);
        register_rest_route(self::NS,'/site-identity',['methods'=>'POST','permission_callback'=>fn()=>current_user_can('edit_theme_options'),'callback'=>[__CLASS__,'save_site_identity']]);
        register_rest_route(self::NS,'/theme-status',['methods'=>'GET','permission_callback'=>fn()=>current_user_can('edit_theme_options'),'callback'=>fn()=>rest_ensure_response(self::theme_state())]);
        register_rest_route(self::NS,'/theme-install',['methods'=>'POST','permission_callback'=>fn()=>current_user_can('manage_options')&&current_user_can('switch_themes'),'callback'=>[__CLASS__,'install_theme']]);
        register_rest_route(self::NS,'/theme-activate',['methods'=>'POST','permission_callback'=>fn()=>current_user_can('switch_themes'),'callback'=>[__CLASS__,'activate_theme']]);
    }
    public static function capabilities(){return rest_ensure_response(['connected'=>true,'version'=>self::VERSION,'features'=>['seo_meta','robots_meta','schema','favicon','gutenberg_blocks','full_site_editing','editable_theme','senuke_theme','menus','forms','site_backup','design_package','release_scoped_layout','rollback','theme_runtime','theme_install','site_identity'],'managedDeploymentReady'=>current_user_can('publish_pages')&&current_user_can('upload_files')&&current_user_can('edit_theme_options')&&current_user_can('manage_options')&&current_user_can('switch_themes'),'permissions'=>['publishPages'=>current_user_can('publish_pages'),'uploadMedia'=>current_user_can('upload_files'),'manageNavigationAndDesign'=>current_user_can('edit_theme_options'),'backupAndRollback'=>current_user_can('manage_options'),'switchTheme'=>current_user_can('switch_themes')],'theme'=>self::theme_state()]);}

    public static function optimize_page(WP_REST_Request $r){$id=(int)$r['id'];$d=$r->get_json_params();$canonical=esc_url_raw($d['canonicalUrl']??'');if($canonical&&strpos($canonical,'/')===0)$canonical=home_url($canonical);$fields=['_senuke_meta_title'=>sanitize_text_field($d['metaTitle']??''),'_senuke_meta_description'=>sanitize_textarea_field($d['metaDescription']??''),'_senuke_canonical_url'=>$canonical,'_senuke_robots'=>sanitize_text_field($d['robots']??'index, follow'),'_senuke_schema_json'=>wp_json_encode($d['schemaJsonLd']??new stdClass()),'_senuke_aeo_reviewed'=>!empty($d['aeoReviewed'])?'1':'0','_senuke_geo_reviewed'=>!empty($d['geoReviewed'])?'1':'0','_senuke_release_id'=>sanitize_text_field($d['approvedReleaseId']??''),'_senuke_snapshot_hash'=>sanitize_text_field($d['snapshotHash']??''),'_senuke_page_id'=>sanitize_text_field($d['senukePageId']??'')];foreach($fields as $k=>$v)update_post_meta($id,$k,$v);self::identity_from_schema($d['schemaJsonLd']??null,$d);return rest_ensure_response(['updated'=>true,'postId'=>$id]);}
    public static function head_meta(){if(!is_singular())return;$id=get_queried_object_id();$description=get_post_meta($id,'_senuke_meta_description',true);$canonical=get_post_meta($id,'_senuke_canonical_url',true);$schema=get_post_meta($id,'_senuke_schema_json',true);$identity=self::current_identity();$favicon=esc_url($identity['faviconUrl']??'');if($description)echo '<meta name="description" content="'.esc_attr($description).'">'."\n";if($canonical){if(strpos($canonical,'/')===0)$canonical=home_url($canonical);remove_action('wp_head','rel_canonical');echo '<link rel="canonical" href="'.esc_url($canonical).'">'."\n";}if($favicon)echo '<link rel="icon" href="'.$favicon.'">'."\n";if($schema&&json_decode($schema))echo '<script type="application/ld+json">'.wp_json_encode(json_decode($schema)).'</script>'."\n";}
    public static function document_title($title){if(!is_singular())return $title;$saved=get_post_meta(get_queried_object_id(),'_senuke_meta_title',true);return $saved?:$title;}
    public static function robots_directives($robots){if(!is_singular())return $robots;$saved=strtolower((string)get_post_meta(get_queried_object_id(),'_senuke_robots',true));if(!$saved)return $robots;foreach(['index','noindex','follow','nofollow','noarchive','nosnippet'] as $directive){if(strpos($saved,$directive)!==false)$robots[$directive]=true;}if(isset($robots['index'])&&isset($robots['noindex']))unset($robots['index']);if(isset($robots['follow'])&&isset($robots['nofollow']))unset($robots['follow']);return $robots;}
    private static function current_release_id(){return is_singular()?(string)get_post_meta(get_queried_object_id(),'_senuke_release_id',true):'';}
    private static function current_design_package(){$release=self::current_release_id();$packages=get_option(self::STYLE_RELEASES_OPTION,[]);if($release&&is_array($packages)&&isset($packages[$release])&&is_array($packages[$release]))return $packages[$release];$legacy=get_option(self::STYLE_OPTION,[]);return is_array($legacy)&&(!$release||empty($legacy['releaseId'])||hash_equals((string)$legacy['releaseId'],$release))?$legacy:[];}
    private static function current_identity(){$release=self::current_release_id();$identities=get_option(self::IDENTITY_RELEASES_OPTION,[]);if($release&&is_array($identities)&&isset($identities[$release])&&is_array($identities[$release]))return $identities[$release];$legacy=get_option(self::IDENTITY_OPTION,[]);return is_array($legacy)?$legacy:[];}
    public static function identity_shortcode($atts){
        $field=sanitize_key(shortcode_atts(['field'=>'brand'],$atts)['field']);
        $identity=self::current_identity();
        if($field==='summary')return esc_html($identity['businessSummary']??'');
        if($field==='copyright')return esc_html($identity['copyrightText']??('© '.gmdate('Y').' '.($identity['businessName']??get_bloginfo('name')).'. All rights reserved.'));
        if(in_array($field,['social','header_social'],true)){$links=self::release_social_links($identity);return $field==='header_social'?str_replace('class="senuke-social-links"','class="senuke-social-links senuke-header-social"',$links):$links;}
        if($field==='contact'){
            $items=[];
            if(!empty($identity['businessAddress']))$items[]='<span>'.esc_html($identity['businessAddress']).'</span>';
            if(!empty($identity['contactPhone']))$items[]='<a href="tel:'.esc_attr(preg_replace('/[^\d+]/','',(string)$identity['contactPhone'])).'">'.esc_html($identity['contactPhone']).'</a>';
            if(!empty($identity['contactEmail']))$items[]='<a href="mailto:'.esc_attr($identity['contactEmail']).'">'.esc_html($identity['contactEmail']).'</a>';
            return'<span class="senuke-theme-contact">'.implode('<span aria-hidden="true"> · </span>',$items).'</span>';
        }
        return esc_html($identity['businessName']??get_bloginfo('name'));
    }
    public static function enqueue_design_package(){$p=self::current_design_package();$css=$p['css']??'';if(!$css)return;$scope=sanitize_key($p['scope']??'release_pages');if($scope==='release_pages'){if(!is_singular())return;$expected=(string)($p['releaseId']??'');$actual=self::current_release_id();if(!$expected||!$actual||!hash_equals($expected,$actual))return;}wp_register_style('senuke-ai-approved-release',false,[],(string)($p['snapshotHash']??self::VERSION));wp_enqueue_style('senuke-ai-approved-release');wp_add_inline_style('senuke-ai-approved-release',$css);}

    private static function is_release_page(){if(!is_singular())return false;$p=self::current_design_package();if(empty($p['css'])||sanitize_key($p['scope']??'release_pages')!=='release_pages')return false;$expected=(string)($p['releaseId']??'');$actual=self::current_release_id();return $expected!==''&&$actual!==''&&hash_equals($expected,$actual);}
    private static function release_menu($name,$class,$location=''){
        static $instance=0;$release=self::current_release_id();$menu=$release?wp_get_nav_menu_object($name.' '.$release):null;if(!$menu)$menu=wp_get_nav_menu_object($name);if(!$menu){$managed=get_option(self::MENU_OPTION,[]);$managed_id=is_array($managed)?absint($managed[sanitize_key($location)]??0):0;if($managed_id)$menu=wp_get_nav_menu_object($managed_id);}if(!$menu)return'';
        $instance++;$html=wp_nav_menu(['menu'=>(int)$menu->term_id,'container'=>'nav','container_class'=>$class,'menu_class'=>'senuke-menu','menu_id'=>sanitize_html_class($class.'-items-'.$instance),'fallback_cb'=>false,'depth'=>8,'echo'=>false]);if(!is_string($html))return'';
        if($location==='footer')$html=preg_replace_callback('~<a\s+([^>]*\s)?href=(["\'])#\2([^>]*)>(.*?)</a>~is',static fn($match)=>'<span class="senuke-menu-heading">'.$match[4].'</span>',$html)??$html;
        return$html;
    }
    private static function release_brand($identity){$name=trim((string)($identity['businessName']??''))?:get_bloginfo('name');$logo=esc_url($identity['logoUrl']??'');return $logo?'<img class="senuke-brand-logo" src="'.$logo.'" alt="'.esc_attr($name.' logo').'">':esc_html($name);}
    private static function release_social_links($identity){$links=[];foreach((array)($identity['socialProfiles']??[]) as $profile){if(!is_array($profile))continue;$network=sanitize_text_field($profile['network']??'');$url=esc_url($profile['url']??'');if(!$network||!$url)continue;$label=ucwords(str_replace(['_','-'],' ',$network));$links[]='<a href="'.$url.'" target="_blank" rel="noopener noreferrer" aria-label="'.esc_attr($label).'"><span aria-hidden="true">'.esc_html(strtoupper(substr($label,0,2))).'</span></a>';}return $links?'<div class="senuke-social-links">'.implode('',$links).'</div>':'';}
    public static function footer_legal_shortcode(){$links=['<a href="'.esc_url(home_url('/wp-sitemap.xml')).'">Sitemap</a>'];$privacy=get_privacy_policy_url();if($privacy)$links[]='<a href="'.esc_url($privacy).'">Privacy Policy</a>';foreach(['terms-of-use','terms-and-conditions','terms']as$slug){$page=get_page_by_path($slug);if($page){$links[]='<a href="'.esc_url(get_permalink($page)).'">Terms of use</a>';break;}}return'<nav class="senuke-footer-legal" aria-label="Legal">'.implode('',$links).'</nav>';}
    public static function render_release_page(){
        if(!self::is_release_page())return;
        if(function_exists('wp_is_block_theme')&&wp_is_block_theme()&&wp_get_theme()->get_stylesheet()===self::THEME_STYLESHEET)return;
        $identity=self::current_identity();
        $brand=self::release_brand($identity);
        $primary=self::release_menu('SENuke Primary Navigation','senuke-primary-nav','primary');
        $footer=self::release_menu('SENuke Footer Navigation','senuke-footer-navigation','footer');
        $social=self::release_social_links($identity);
        $header_social=str_replace('class="senuke-social-links"','class="senuke-social-links senuke-header-social"',$social);
        $summary=trim((string)($identity['businessSummary']??''));
        $contact=[];
        if(!empty($identity['businessAddress']))$contact[]='<span>'.esc_html($identity['businessAddress']).'</span>';
        if(!empty($identity['contactPhone']))$contact[]='<a href="tel:'.esc_attr(preg_replace('/[^\d+]/','',(string)$identity['contactPhone'])).'">'.esc_html($identity['contactPhone']).'</a>';
        if(!empty($identity['contactEmail']))$contact[]='<a href="mailto:'.esc_attr($identity['contactEmail']).'">'.esc_html($identity['contactEmail']).'</a>';
        status_header(200);?><!doctype html><html <?php language_attributes();?>><head><meta charset="<?php bloginfo('charset');?>"><meta name="viewport" content="width=device-width,initial-scale=1"><?php wp_head();?></head><body <?php body_class('senuke-release-page');?>><?php wp_body_open();?><div class="senuke-site-topbar"><div class="senuke-site-topbar-inner"><?php echo $header_social;?><?php if($contact):?><div class="senuke-header-contact"><?php echo implode('',$contact);?></div><?php endif;?></div></div><header class="senuke-site-header"><a class="senuke-brand" href="<?php echo esc_url(home_url('/'));?>"><?php echo $brand;?></a><div class="senuke-header-navigation"><?php echo $primary;?></div><details class="senuke-mobile-menu"><summary aria-label="Open navigation menu"><span class="senuke-menu-icon" aria-hidden="true"><i></i><i></i><i></i></span><span class="senuke-visually-hidden">Menu</span></summary><div class="senuke-mobile-menu-panel"><?php echo $primary;?></div></details></header><main><?php while(have_posts()):the_post();the_content();endwhile;?></main><footer class="senuke-site-footer"><div class="senuke-footer-main"><section class="senuke-footer-brand"><a class="senuke-footer-logo" href="<?php echo esc_url(home_url('/'));?>"><?php echo $brand;?></a><?php if($summary):?><p><?php echo esc_html($summary);?></p><?php endif;echo $social;?></section><div class="senuke-footer-navigation-column"><?php echo $footer;?></div><section class="senuke-footer-contact-column"><h2>Get in touch</h2><?php if($contact):?><div class="senuke-footer-contact"><?php echo implode('',$contact);?></div><?php endif;?></section></div><div class="senuke-footer-bottom"><p class="senuke-footer-copyright"><?php echo esc_html($identity['copyrightText']??('© '.gmdate('Y').' '.get_bloginfo('name').'. All rights reserved.'));?></p><?php echo self::footer_legal_shortcode();?></div></footer><?php wp_footer();?></body></html><?php exit;
    }

    public static function create_menu(WP_REST_Request $r){
        $d=$r->get_json_params();$name=sanitize_text_field($d['name']??'SENuke Primary Navigation');$menu=wp_get_nav_menu_object($name);$id=$menu?(int)$menu->term_id:wp_create_nav_menu($name);if(is_wp_error($id))return$id;
        foreach(wp_get_nav_menu_items($id)?:[]as$old)wp_delete_post($old->ID,true);
        $created=[];$pending=array_values((array)($d['items']??[]));$pos=1;
        for($pass=0;$pass<100&&$pending;$pass++){$remaining=[];foreach($pending as$item){if(!is_array($item))continue;$source=sanitize_key($item['id']??'');$parent=sanitize_key($item['parentId']??'');if($parent&&empty($created[$parent])){$remaining[]=$item;continue;}$new=wp_update_nav_menu_item($id,0,['menu-item-title'=>sanitize_text_field($item['label']??'Page'),'menu-item-url'=>esc_url_raw($item['url']??home_url('/')),'menu-item-parent-id'=>$parent?(int)$created[$parent]:0,'menu-item-status'=>'publish','menu-item-position'=>$pos++]);if(!is_wp_error($new)&&$source)$created[$source]=(int)$new;}if(count($remaining)===count($pending))break;$pending=$remaining;}
        $locations=get_theme_mod('nav_menu_locations',[]);$registered=get_registered_nav_menus();$requested=sanitize_key($d['location']??'');if(!in_array($requested,['primary','footer'],true))$requested='primary';$assign=!empty($d['assignLocation']);$preferred=isset($registered[$requested])?$requested:null;if(!$preferred&&$requested==='footer')foreach(array_keys($registered)as$loc)if(preg_match('/footer|bottom|secondary/i',$loc)){$preferred=$loc;break;}if(!$preferred&&$requested!=='footer')$preferred=isset($registered['primary'])?'primary':array_key_first($registered);
        if($assign){if($preferred){$locations[$preferred]=$id;set_theme_mod('nav_menu_locations',$locations);}$managed=get_option(self::MENU_OPTION,[]);if(!is_array($managed))$managed=[];$managed[$requested]=(int)$id;update_option(self::MENU_OPTION,$managed,false);}
        return rest_ensure_response(['menuId'=>$id,'location'=>$preferred,'managedLocation'=>$requested,'itemCount'=>count($created)]);
    }

    public static function save_form(WP_REST_Request $r){$d=$r->get_json_params();$key=sanitize_key($d['key']??'primary_contact');$forms=get_option(self::FORM_OPTION,[]);if(!is_array($forms))$forms=[];$fields=[];foreach((array)($d['fields']??[]) as $f){if(is_array($f)){$label=sanitize_text_field($f['label']??$f['name']??'Field');$name=sanitize_key($f['name']??$label);$type=sanitize_key($f['inputType']??$f['type']??'text');if(!in_array($type,['text','email','tel','textarea','checkbox'],true))$type='text';$fields[]=['label'=>$label,'name'=>$name,'inputType'=>$type,'required'=>!empty($f['required'])];}else{$label=sanitize_text_field($f);$fields[]=['label'=>$label,'name'=>sanitize_key($label),'inputType'=>preg_match('/message|details/i',$label)?'textarea':(stripos($label,'email')!==false?'email':'text'),'required'=>true];}}$forms[$key]=['name'=>sanitize_text_field($d['name']??'Contact form'),'fields'=>$fields,'submitLabel'=>sanitize_text_field($d['submitLabel']??'Submit'),'successMessage'=>sanitize_text_field($d['successMessage']??'Thank you. Your enquiry has been received.'),'destination'=>sanitize_email($d['destination']??get_option('admin_email'))];update_option(self::FORM_OPTION,$forms,false);return rest_ensure_response(['key'=>$key,'shortcode'=>'[senuke_form id="'.esc_attr($key).'"]']);}
    public static function form_shortcode($atts){$id=sanitize_key(shortcode_atts(['id'=>'primary_contact'],$atts)['id']);$forms=get_option(self::FORM_OPTION,[]);$form=is_array($forms)?($forms[$id]??null):null;if(!$form)return'';ob_start();?><form class="senuke-ai-form" method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="senuke_form_submit"><input type="hidden" name="senuke_form_id" value="<?php echo esc_attr($id);?>"><?php wp_nonce_field('senuke_form_'.$id,'senuke_nonce');foreach($form['fields'] as $f):$name=sanitize_key($f['name']??$f['label']);$type=$f['inputType']??'text';$req=!empty($f['required']);?><p><label><?php echo esc_html($f['label']);?><br><?php if($type==='textarea'):?><textarea name="<?php echo esc_attr($name);?>" <?php echo $req?'required':'';?>></textarea><?php elseif($type==='checkbox'):?><input name="<?php echo esc_attr($name);?>" type="checkbox" value="yes" <?php echo $req?'required':'';?>><?php else:?><input name="<?php echo esc_attr($name);?>" type="<?php echo esc_attr(in_array($type,['email','tel'],true)?$type:'text');?>" <?php echo $req?'required':'';?>><?php endif;?></label></p><?php endforeach;?><button type="submit"><?php echo esc_html($form['submitLabel']);?></button></form><?php return ob_get_clean();}
    public static function form_submit(){$id=sanitize_key($_POST['senuke_form_id']??'');if(!$id||!wp_verify_nonce($_POST['senuke_nonce']??'','senuke_form_'.$id))wp_die('Invalid form request.',403);$forms=get_option(self::FORM_OPTION,[]);$form=is_array($forms)?($forms[$id]??null):null;if(!$form)wp_die('Form unavailable.',404);$lines=[];foreach($form['fields'] as $f){$name=sanitize_key($f['name']??$f['label']);$lines[]=$f['label'].': '.sanitize_textarea_field(wp_unslash($_POST[$name]??''));}wp_mail($form['destination'],'Website enquiry: '.$form['name'],implode("\n",$lines));wp_safe_redirect(add_query_arg('senuke_enquiry','received',wp_get_referer()?:home_url('/')));exit;}

    public static function create_backup(WP_REST_Request $r){$d=$r->get_json_params();$id=sanitize_key('senuke-'.gmdate('Ymd-His').'-'.wp_generate_password(6,false,false));$theme=wp_get_theme();$snapshot=['backupId'=>$id,'createdAt'=>gmdate('c'),'releaseId'=>sanitize_text_field($d['releaseId']??''),'snapshotHash'=>sanitize_text_field($d['snapshotHash']??''),'site'=>['blogname'=>get_option('blogname'),'blogdescription'=>get_option('blogdescription'),'show_on_front'=>get_option('show_on_front'),'page_on_front'=>(int)get_option('page_on_front'),'page_for_posts'=>(int)get_option('page_for_posts'),'permalink_structure'=>get_option('permalink_structure')],'theme'=>['stylesheet'=>$theme->get_stylesheet()],'navigationLocations'=>get_theme_mod('nav_menu_locations',[]),'managedNavigationMenus'=>get_option(self::MENU_OPTION,[]),'designPackage'=>get_option(self::STYLE_OPTION,[]),'releaseDesignPackages'=>get_option(self::STYLE_RELEASES_OPTION,[]),'forms'=>get_option(self::FORM_OPTION,[]),'identity'=>get_option(self::IDENTITY_OPTION,[]),'releaseIdentities'=>get_option(self::IDENTITY_RELEASES_OPTION,[])];$backups=get_option(self::BACKUP_OPTION,[]);if(!is_array($backups))$backups=[];$backups[$id]=$snapshot;if(count($backups)>20)$backups=array_slice($backups,-20,null,true);update_option(self::BACKUP_OPTION,$backups,false);return rest_ensure_response(['backupId'=>$id,'createdAt'=>$snapshot['createdAt']]);}
    public static function restore_backup(WP_REST_Request $r){$id=sanitize_key($r['id']);$backups=get_option(self::BACKUP_OPTION,[]);$s=is_array($backups)?($backups[$id]??null):null;if(!$s)return new WP_Error('senuke_backup_not_found','The requested SENuke deployment backup was not found.',['status'=>404]);foreach((array)($s['site']??[]) as $k=>$v)update_option(sanitize_key($k),$v);$previous=sanitize_key($s['theme']['stylesheet']??'');if($previous&&wp_get_theme($previous)->exists()&&current_user_can('switch_themes'))switch_theme($previous);set_theme_mod('nav_menu_locations',(array)($s['navigationLocations']??[]));update_option(self::MENU_OPTION,(array)($s['managedNavigationMenus']??[]),false);update_option(self::STYLE_OPTION,(array)($s['designPackage']??[]),false);update_option(self::STYLE_RELEASES_OPTION,(array)($s['releaseDesignPackages']??[]),false);update_option(self::FORM_OPTION,(array)($s['forms']??[]),false);update_option(self::IDENTITY_OPTION,(array)($s['identity']??[]),false);update_option(self::IDENTITY_RELEASES_OPTION,(array)($s['releaseIdentities']??[]),false);flush_rewrite_rules(false);return rest_ensure_response(['restored'=>true,'backupId'=>$id,'restoredAt'=>gmdate('c')]);}

    public static function save_design_package(WP_REST_Request $r){
        $d=$r->get_json_params();
        $css=(string)($d['css']??'');
        if(strlen($css)>350000)return new WP_Error('senuke_css_too_large','The approved design package exceeds 350 KB.',['status'=>413]);
        if(preg_match('/(?:<\/?style\b|<script\b|@import\b|url\s*\(\s*["\']?\s*javascript\s*:|expression\s*\(|(?:^|[;{])\s*behavior\s*:|-moz-binding\s*:)/i',$css))return new WP_Error('senuke_css_rejected','The design package contains an unsupported CSS construct.',['status'=>400]);
        $scope=sanitize_key($d['scope']??'release_pages');
        if(!in_array($scope,['release_pages','global'],true))$scope='release_pages';
        $p=['releaseId'=>sanitize_text_field($d['releaseId']??''),'snapshotHash'=>sanitize_text_field($d['snapshotHash']??''),'scope'=>$scope,'css'=>$css,'savedAt'=>gmdate('c')];
        if(!$p['releaseId'])return new WP_Error('senuke_release_required','A release ID is required for the design package.',['status'=>400]);
        $packages=get_option(self::STYLE_RELEASES_OPTION,[]);
        if(!is_array($packages))$packages=[];
        $packages[$p['releaseId']]=$p;
        if(count($packages)>20)$packages=array_slice($packages,-20,null,true);
        update_option(self::STYLE_RELEASES_OPTION,$packages,false);

        $theme=self::theme_state();
        $activate_theme=!empty($d['activateTheme']);
        $refresh_active_senuke_theme=!$activate_theme&&$theme['active'];
        if($activate_theme||$refresh_active_senuke_theme){
            if($activate_theme)update_option(self::STYLE_OPTION,$p,false);
            if(!current_user_can('manage_options')||!current_user_can('switch_themes'))return new WP_Error('senuke_theme_permission_required','Refreshing SENuke Theme requires a WordPress administrator who can install and switch themes.',['status'=>403]);
            try{
                // Draft synchronization must refresh the bundled files when
                // SENuke Theme is already active. It does not switch themes or
                // publish pages; it only updates the editable theme package.
                $installed=self::ensure_theme();
                if(is_wp_error($installed))return $installed;
                if($activate_theme&&wp_get_theme()->get_stylesheet()!==self::THEME_STYLESHEET){
                    switch_theme(self::THEME_STYLESHEET);
                    self::refresh_theme_cache();
                }
                $theme=self::theme_state();
                if($activate_theme&&!$theme['active'])return new WP_Error('senuke_theme_not_activated','WordPress wrote the SENuke Theme files but did not activate the theme. Check wp-content/themes permissions and whether theme changes are disabled by the host.',['status'=>409]);
            }catch(Throwable $e){
                $detail=sanitize_text_field($e->getMessage());
                return new WP_Error('senuke_theme_activation_failed','WordPress could not install or refresh SENuke Theme'.($detail?': '.$detail:'.').' Keep the current theme active and check the server theme/file permissions before retrying.',['status'=>500]);
            }
        }
        return rest_ensure_response(['installed'=>$theme['installed'],'activated'=>$theme['active'],'scope'=>$scope,'releaseId'=>$p['releaseId'],'snapshotHash'=>$p['snapshotHash'],'bytes'=>strlen($css),'theme'=>$theme]);
    }
    public static function theme_state(){$t=wp_get_theme(self::THEME_STYLESHEET);$a=wp_get_theme();return['stylesheet'=>self::THEME_STYLESHEET,'installed'=>$t->exists(),'active'=>$a->get_stylesheet()===self::THEME_STYLESHEET,'version'=>$t->exists()?(string)$t->get('Version'):'','fullSiteEditing'=>$a->get_stylesheet()===self::THEME_STYLESHEET&&function_exists('wp_is_block_theme')&&wp_is_block_theme(),'activeStylesheet'=>$a->get_stylesheet(),'activeTheme'=>$a->get('Name')];}
    public static function install_theme(WP_REST_Request $r){$d=$r->get_json_params();$encoded=preg_replace('/\s+/','',(string)($d['packageBase64']??''));if(!$encoded){$result=self::ensure_theme();if(is_wp_error($result))return$result;if(!empty($d['activate']))switch_theme(self::THEME_STYLESHEET);self::refresh_theme_cache();return rest_ensure_response(['installed'=>true,'activated'=>wp_get_theme()->get_stylesheet()===self::THEME_STYLESHEET,'theme'=>self::theme_state()]);}$bytes=base64_decode($encoded,true);if($bytes===false||strlen($bytes)<100)return new WP_Error('senuke_theme_package_invalid','The SENuke Theme package is invalid.',['status'=>400]);require_once ABSPATH.'wp-admin/includes/file.php';if(!WP_Filesystem())return new WP_Error('senuke_filesystem_unavailable','WordPress could not initialize filesystem access.',['status'=>409]);$tmp=wp_tempnam('senuke-theme.zip');if(!$tmp||file_put_contents($tmp,$bytes)===false)return new WP_Error('senuke_theme_temp_failed','WordPress could not create a temporary theme package.',['status'=>500]);$result=unzip_file($tmp,get_theme_root());@unlink($tmp);if(is_wp_error($result))return$result;self::refresh_theme_cache();if(!empty($d['activate']))switch_theme(self::THEME_STYLESHEET);return rest_ensure_response(['installed'=>true,'activated'=>wp_get_theme()->get_stylesheet()===self::THEME_STYLESHEET,'theme'=>self::theme_state()]);}
    public static function activate_theme(){if(!wp_get_theme(self::THEME_STYLESHEET)->exists())return new WP_Error('senuke_theme_not_installed','Install SENuke Theme first.',['status'=>409]);switch_theme(self::THEME_STYLESHEET);return rest_ensure_response(['activated'=>true,'theme'=>self::theme_state()]);}
    private static function ensure_theme(){
        if(function_exists('wp_is_file_mod_allowed')&&!wp_is_file_mod_allowed('senuke_ai_theme'))return new WP_Error('senuke_theme_file_mods_disabled','This WordPress installation has theme file changes disabled. Ask the host or administrator to allow theme installation, then retry.',['status'=>409]);
        require_once ABSPATH.'wp-admin/includes/file.php';
        $filesystem_ready=WP_Filesystem();
        global $wp_filesystem;
        $root=trailingslashit(get_theme_root()).self::THEME_STYLESHEET;
        $files=self::theme_files();
        if($filesystem_ready&&$wp_filesystem){
            $dir_mode=defined('FS_CHMOD_DIR')?FS_CHMOD_DIR:0755;
            $file_mode=defined('FS_CHMOD_FILE')?FS_CHMOD_FILE:0644;
            if(!$wp_filesystem->is_dir($root)&&!$wp_filesystem->mkdir($root,$dir_mode))return new WP_Error('senuke_theme_directory_failed','WordPress could not create wp-content/themes/senuke-theme. Check the themes directory permissions.',['status'=>409]);
            foreach($files as $path=>$content){$target=$root.'/'.$path;$dir=dirname($target);if(!$wp_filesystem->is_dir($dir)&&!$wp_filesystem->mkdir($dir,$dir_mode))return new WP_Error('senuke_theme_subdirectory_failed','WordPress could not create the SENuke theme template directories. Check wp-content/themes permissions.',['status'=>409]);if(!$wp_filesystem->put_contents($target,$content,$file_mode))return new WP_Error('senuke_theme_write_failed','WordPress could not write '.$path.' in wp-content/themes/senuke-theme. Check file ownership and permissions.',['status'=>409]);}
        }else{
            if(!is_dir($root)&&!wp_mkdir_p($root))return new WP_Error('senuke_theme_directory_failed','WordPress filesystem access needs credentials and direct creation of wp-content/themes/senuke-theme also failed. Configure direct filesystem access or install the theme manually.',['status'=>409]);
            foreach($files as $path=>$content){$target=$root.'/'.$path;$dir=dirname($target);if(!is_dir($dir)&&!wp_mkdir_p($dir))return new WP_Error('senuke_theme_subdirectory_failed','WordPress could not create the SENuke theme template directories.',['status'=>409]);if(file_put_contents($target,$content,LOCK_EX)===false)return new WP_Error('senuke_theme_write_failed','WordPress could not write '.$path.' using direct filesystem access. Check wp-content/themes ownership and permissions.',['status'=>409]);}
        }
        self::refresh_theme_cache();
        $theme=wp_get_theme(self::THEME_STYLESHEET);
        if(!$theme->exists())return new WP_Error('senuke_theme_invalid','The SENuke theme files were written, but WordPress does not recognize the theme. Check the generated style.css and theme directory.',['status'=>409]);
        $errors=$theme->errors();
        if(is_wp_error($errors))return new WP_Error('senuke_theme_invalid','WordPress rejected SENuke Theme: '.$errors->get_error_message(),['status'=>409]);
        return['installed'=>true,'theme'=>self::theme_state()];
    }
    private static function refresh_theme_cache(){if(function_exists('wp_clean_themes_cache'))wp_clean_themes_cache(true);}
    private static function theme_files(){
        $bundled_root=trailingslashit(plugin_dir_path(__FILE__)).'theme/'.self::THEME_STYLESHEET;
        $bundled=[];
        if(is_dir($bundled_root)&&class_exists('RecursiveDirectoryIterator')){
            $iterator=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($bundled_root,FilesystemIterator::SKIP_DOTS));
            foreach($iterator as $file){if(!$file->isFile())continue;$path=str_replace('\\','/',substr($file->getPathname(),strlen($bundled_root)+1));$content=file_get_contents($file->getPathname());if($content!==false)$bundled[$path]=$content;}
        }
        if(isset($bundled['style.css'],$bundled['functions.php'],$bundled['theme.json'],$bundled['templates/index.html'],$bundled['parts/header.html'],$bundled['parts/footer.html']))return$bundled;
        $theme_json=wp_json_encode([
            'version'=>2,
            'settings'=>[
                'appearanceTools'=>true,
                'layout'=>['contentSize'=>'760px','wideSize'=>'1240px'],
                'color'=>['defaultPalette'=>true,'defaultGradients'=>true,'custom'=>true,'customGradient'=>true,'link'=>true,'palette'=>[
                    ['slug'=>'base','name'=>'Base','color'=>'#ffffff'],
                    ['slug'=>'contrast','name'=>'Contrast','color'=>'#0f172a'],
                    ['slug'=>'primary','name'=>'Primary','color'=>'#2563eb'],
                    ['slug'=>'accent','name'=>'Accent','color'=>'#0f766e'],
                ]],
                'spacing'=>['blockGap'=>true,'margin'=>true,'padding'=>true,'units'=>['px','rem','em','%','vw','vh']],
                'typography'=>['customFontSize'=>true,'dropCap'=>true,'fluid'=>true,'fontStyle'=>true,'fontWeight'=>true,'letterSpacing'=>true,'lineHeight'=>true,'textDecoration'=>true,'textTransform'=>true],
                'border'=>['color'=>true,'radius'=>true,'style'=>true,'width'=>true],
                'dimensions'=>['minHeight'=>true],
                'position'=>['sticky'=>true],
            ],
            'styles'=>[
                'color'=>['background'=>'#ffffff','text'=>'#172033'],
                'spacing'=>['blockGap'=>'1.5rem'],
                'typography'=>['fontFamily'=>'-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif','lineHeight'=>'1.65'],
                'elements'=>['button'=>['border'=>['radius'=>'6px'],'typography'=>['fontWeight'=>'700']]],
            ],
            'templateParts'=>[
                ['name'=>'header','title'=>'Header','area'=>'header'],
                ['name'=>'footer','title'=>'Footer','area'=>'footer'],
            ],
        ],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES);
        $header='<!-- wp:group {"align":"full","className":"senuke-site-topbar","layout":{"type":"default"}} --><div class="wp-block-group alignfull senuke-site-topbar"><!-- wp:group {"className":"senuke-site-topbar-inner","layout":{"type":"flex","flexWrap":"wrap","justifyContent":"space-between"}} --><div class="wp-block-group senuke-site-topbar-inner"><!-- wp:shortcode -->[senuke_identity field="header_social"]<!-- /wp:shortcode --><!-- wp:shortcode -->[senuke_identity field="contact"]<!-- /wp:shortcode --></div><!-- /wp:group --></div><!-- /wp:group --><!-- wp:group {"align":"full","className":"senuke-site-header","layout":{"type":"flex","flexWrap":"wrap","justifyContent":"space-between"}} --><div class="wp-block-group alignfull senuke-site-header"><!-- wp:group {"className":"senuke-brand","layout":{"type":"flex","flexWrap":"nowrap"}} --><div class="wp-block-group senuke-brand"><!-- wp:site-logo {"width":72,"shouldSyncIcon":true} /--><!-- wp:site-title {"level":0,"style":{"typography":{"fontWeight":"800"}}} /--></div><!-- /wp:group --><!-- wp:senuke/navigation {"componentId":"global.navigation","props":{"location":"primary"}} /--></div><!-- /wp:group -->';
        $footer='<!-- wp:group {"align":"full","className":"senuke-site-footer","layout":{"type":"default"}} --><div class="wp-block-group alignfull senuke-site-footer"><!-- wp:columns {"className":"senuke-footer-main"} --><div class="wp-block-columns senuke-footer-main"><!-- wp:column {"className":"senuke-footer-brand"} --><div class="wp-block-column senuke-footer-brand"><!-- wp:site-logo {"width":180} /--><!-- wp:site-title {"level":0,"isLink":true,"style":{"typography":{"fontWeight":"800","fontSize":"24px"}}} /--><!-- wp:shortcode -->[senuke_identity field="summary"]<!-- /wp:shortcode --><!-- wp:shortcode -->[senuke_identity field="social"]<!-- /wp:shortcode --></div><!-- /wp:column --><!-- wp:column {"className":"senuke-footer-navigation-column"} --><div class="wp-block-column senuke-footer-navigation-column"><!-- wp:senuke/navigation {"componentId":"global.navigation","props":{"location":"footer"}} /--></div><!-- /wp:column --><!-- wp:column {"className":"senuke-footer-contact-column"} --><div class="wp-block-column senuke-footer-contact-column"><!-- wp:heading {"level":3,"fontSize":"medium"} --><h3 class="wp-block-heading has-medium-font-size">Get in touch</h3><!-- /wp:heading --><!-- wp:shortcode -->[senuke_identity field="contact"]<!-- /wp:shortcode --></div><!-- /wp:column --></div><!-- /wp:columns --><div class="senuke-footer-bottom"><!-- wp:shortcode -->[senuke_identity field="copyright"]<!-- /wp:shortcode --><!-- wp:shortcode -->[senuke_footer_legal]<!-- /wp:shortcode --></div></div><!-- /wp:group -->';
        $page_template='<!-- wp:template-part {"slug":"header","tagName":"header"} /--><!-- wp:group {"tagName":"main","align":"full","className":"senuke-theme-main","layout":{"type":"default"}} --><main class="wp-block-group alignfull senuke-theme-main"><!-- wp:post-content {"layout":{"type":"default"}} /--></main><!-- /wp:group --><!-- wp:template-part {"slug":"footer","tagName":"footer"} /-->';
        $single_template='<!-- wp:template-part {"slug":"header","tagName":"header"} /--><!-- wp:group {"tagName":"main","style":{"spacing":{"padding":{"top":"40px","bottom":"56px","left":"20px","right":"20px"}}},"layout":{"type":"constrained"}} --><main class="wp-block-group" style="padding-top:40px;padding-right:20px;padding-bottom:56px;padding-left:20px"><!-- wp:post-title {"level":1} /--><!-- wp:post-content /--></main><!-- /wp:group --><!-- wp:template-part {"slug":"footer","tagName":"footer"} /-->';
        $index_template='<!-- wp:template-part {"slug":"header","tagName":"header"} /--><!-- wp:query {"query":{"perPage":10,"postType":"post","order":"desc","orderBy":"date"},"layout":{"type":"constrained"}} --><div class="wp-block-query"><!-- wp:post-template --><!-- wp:post-title {"isLink":true} /--><!-- wp:post-excerpt /--><!-- /wp:post-template --><!-- wp:query-pagination /--></div><!-- /wp:query --><!-- wp:template-part {"slug":"footer","tagName":"footer"} /-->';
        return[
            'style.css'=>"/*\nTheme Name: SENuke Theme\nAuthor: SENuke AI\nDescription: Fully editable WordPress block theme generated and managed by SENuke AI.\nVersion: 1.0.0\nRequires at least: 6.4\n*/\nhtml{scroll-behavior:smooth}body{margin:0}.senuke-inline-underline{text-decoration:underline}.wp-site-blocks{min-height:100vh;padding:0}.wp-site-blocks>.wp-block-template-part{margin:0}.senuke-theme-main,.wp-block-post-content{max-width:none!important;margin:0!important;padding:0!important}.wp-block-navigation-item__content{text-decoration:none}.senuke-site-header .wp-block-site-title{margin:0}.senuke-site-header .wp-block-site-title a{text-decoration:none}.senuke-site-header .wp-block-site-logo+.wp-block-site-title,.senuke-footer-brand .wp-block-site-logo+.wp-block-site-title{display:none}.senuke-site-header .wp-block-navigation{margin-left:auto}.senuke-site-footer{padding:3rem max(1rem,calc((100% - 1120px)/2)) 1.25rem}.senuke-site-footer .senuke-footer-main{width:100%;max-width:1120px;margin:0 auto;display:grid;grid-template-columns:minmax(220px,1.35fr) minmax(150px,.8fr) minmax(180px,1fr) minmax(220px,1.1fr);gap:2.5rem}.senuke-site-footer .wp-block-page-list,.senuke-site-footer .wp-block-navigation__container{list-style:none;margin:0;padding:0}.senuke-site-footer li{margin:.45rem 0}.senuke-site-footer a{text-decoration:none}.senuke-site-footer .senuke-footer-bottom{width:100%;max-width:1120px;margin:2rem auto 0;padding-top:1rem;border-top:1px solid currentColor}.senuke-theme-contact{display:flex;flex-wrap:wrap;gap:.45rem}.senuke-footer-contact-column .senuke-theme-contact{display:grid}.senuke-footer-services .wp-block-navigation__submenu-container{display:block;position:static;width:auto;height:auto;visibility:visible;opacity:1;border:0;background:transparent}.senuke-footer-services .wp-block-page-list>li:not(.has-child){display:none}.senuke-footer-services .wp-block-page-list>li.has-child>a{display:none}.senuke-footer-services .wp-block-page-list>li.has-child>ul{display:block;position:static;width:auto;height:auto;visibility:visible;opacity:1;border:0;background:transparent}.senuke-footer-services .wp-block-page-list>li.has-child>ul li{display:block}@media(max-width:900px){.senuke-site-footer .senuke-footer-main{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.senuke-site-footer .senuke-footer-main{grid-template-columns:1fr}.senuke-site-header{gap:1rem}.senuke-site-header .wp-block-navigation{margin-left:0}}",
            'theme.json'=>$theme_json,
            'functions.php'=>"<?php\nif(!defined('ABSPATH'))exit;\nfunction senuke_theme_setup(){add_theme_support('title-tag');add_theme_support('post-thumbnails');add_theme_support('editor-styles');add_theme_support('wp-block-styles');add_theme_support('responsive-embeds');add_theme_support('align-wide');register_nav_menus(['primary'=>'Primary Navigation','footer'=>'Footer Navigation']);}\nadd_action('after_setup_theme','senuke_theme_setup');\nfunction senuke_theme_assets(){wp_enqueue_style('senuke-theme-style',get_stylesheet_uri(),[],wp_get_theme()->get('Version'));}\nadd_action('wp_enqueue_scripts','senuke_theme_assets');\n",
            'templates/index.html'=>$index_template,
            'templates/page.html'=>$page_template,
            'templates/front-page.html'=>$page_template,
            'templates/single.html'=>$single_template,
            'parts/header.html'=>$header,
            'parts/footer.html'=>$footer,
            'index.php'=>"<?php // Silence is golden. WordPress uses templates/index.html.\n",
        ];
    }

    public static function save_site_identity(WP_REST_Request $r){$d=$r->get_json_params();$identity=['releaseId'=>sanitize_text_field($d['releaseId']??''),'snapshotHash'=>sanitize_text_field($d['snapshotHash']??''),'businessName'=>sanitize_text_field($d['businessName']??get_option('blogname')),'businessSummary'=>sanitize_textarea_field($d['businessSummary']??''),'logoUrl'=>esc_url_raw($d['logoUrl']??''),'logoMediaId'=>absint($d['logoMediaId']??0),'faviconUrl'=>esc_url_raw($d['faviconUrl']??''),'faviconMediaId'=>absint($d['faviconMediaId']??0),'contactEmail'=>sanitize_email($d['contactEmail']??''),'contactPhone'=>sanitize_text_field($d['contactPhone']??''),'businessAddress'=>sanitize_text_field($d['businessAddress']??''),'copyrightText'=>sanitize_text_field($d['copyrightText']??''),'socialProfiles'=>(array)($d['socialProfiles']??[])];if(!$identity['releaseId'])return new WP_Error('senuke_release_required','A release ID is required for the site identity.',['status'=>400]);$identities=get_option(self::IDENTITY_RELEASES_OPTION,[]);if(!is_array($identities))$identities=[];$identities[$identity['releaseId']]=$identity;if(count($identities)>20)$identities=array_slice($identities,-20,null,true);update_option(self::IDENTITY_RELEASES_OPTION,$identities,false);if(!empty($d['applySiteSettings'])){update_option(self::IDENTITY_OPTION,$identity,false);if($identity['businessName'])update_option('blogname',$identity['businessName']);if($identity['logoMediaId'])set_theme_mod('custom_logo',$identity['logoMediaId']);if($identity['faviconMediaId'])update_option('site_icon',$identity['faviconMediaId']);}return rest_ensure_response(['saved'=>true,'releaseId'=>$identity['releaseId'],'siteLogoApplied'=>(bool)$identity['logoMediaId'],'siteIconApplied'=>(bool)$identity['faviconMediaId']]);}
    private static function identity_from_schema($schema,$request=[]){if(is_string($schema))$schema=json_decode($schema,true);if(!is_array($schema))return;$release=sanitize_text_field($request['approvedReleaseId']??'');if(!$release)return;$identities=get_option(self::IDENTITY_RELEASES_OPTION,[]);if(!is_array($identities))$identities=[];$current=is_array($identities[$release]??null)?$identities[$release]:['releaseId'=>$release,'snapshotHash'=>sanitize_text_field($request['snapshotHash']??'')];$items=isset($schema['@graph'])&&is_array($schema['@graph'])?$schema['@graph']:[$schema];foreach($items as $item){if(!is_array($item))continue;$types=(array)($item['@type']??[]);if(!array_intersect($types,['Organization','LocalBusiness','ProfessionalService','Corporation']))continue;if(empty($current['businessName']))$current['businessName']=sanitize_text_field($item['name']??'');if(empty($current['contactEmail']))$current['contactEmail']=sanitize_email($item['email']??'');if(empty($current['contactPhone']))$current['contactPhone']=sanitize_text_field($item['telephone']??'');$identities[$release]=$current;update_option(self::IDENTITY_RELEASES_OPTION,$identities,false);break;}}
}
SENuke_AI_Connector::boot();
