import { createCipheriv, createDecipheriv, createHash, createHmac, randomBytes } from "node:crypto";
import { lookup } from "node:dns/promises";
import { isIP } from "node:net";
import { Router, type Request } from "express";
import { Prisma, prisma } from "@webtummy/db";
import { z } from "zod";
import { config } from "../config.js";
import { sendMail } from "../email.js";
import { requireAuth } from "../middleware.js";
import { canAccessProject, createWorkspaceNotification, hasWorkspacePermission, recordWorkspaceActivity, workspaceContext } from "../workspace-access.js";

export const leadMagnetsRouter = Router();
export const publicLeadMagnetsRouter = Router();
leadMagnetsRouter.use(requireAuth);

const providerSchema = z.enum(["mailchimp", "brevo", "aweber", "getresponse", "generic_webhook"]);
const decisionSchema = z.object({ comments: z.string().trim().max(4000).optional().nullable(), shareWithClient: z.boolean().optional() });
const connectionSchema = z.object({
  provider: providerSchema,
  token: z.string().trim().min(1).max(4000).optional(),
  endpointUrl: z.string().url().max(512).optional(),
  accountId: z.string().trim().max(191).optional(),
  listId: z.string().trim().max(191).optional(),
  listName: z.string().trim().min(1).max(180).default("SEnuke AI Leads"),
  fieldMappings: z.record(z.string(), z.string().trim().max(120)).default({ email: "email", firstName: "first_name", lastName: "last_name" }),
});
const metricsSchema = z.object({
  views: z.number().int().min(0).default(0), optIns: z.number().int().min(0).default(0), downloads: z.number().int().min(0).default(0),
  emailsDelivered: z.number().int().min(0).default(0), emailOpens: z.number().int().min(0).default(0), emailClicks: z.number().int().min(0).default(0),
  periodStart: z.coerce.date().optional(), periodEnd: z.coerce.date().optional(), source: z.string().trim().max(40).default("manual"),
});
const editSchema = z.object({
  title: z.string().trim().min(3).max(255).optional(), magnetType: z.string().trim().min(2).max(60).optional(),
  landingHeadline: z.string().trim().min(3).max(240).optional(), landingSubheadline: z.string().trim().min(3).max(600).optional(), ctaText: z.string().trim().min(2).max(120).optional(),
  deliverySubject: z.string().trim().min(2).max(240).optional(), deliveryBody: z.string().trim().min(3).max(10000).optional(),
  conversionTarget: z.number().min(.1).max(100).optional(), sharedWithClient: z.boolean().optional(), comments: z.string().trim().max(2000).optional(),
});
const subscribeSchema = z.object({ email: z.string().email().max(254), firstName: z.string().trim().max(100).optional(), lastName: z.string().trim().max(100).optional(), consent: z.literal(true), website: z.string().max(0).optional() });

const includeFunnel = { espConnection: true, decisions: { orderBy: { createdAt: "desc" as const } }, metrics: { orderBy: { createdAt: "desc" as const }, take: 100 } };
const jsonObject = (value: unknown) => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
const jsonList = (value: unknown) => Array.isArray(value) ? value : [];
const slug = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 80);

function publicConnection<T extends { credentialCiphertext?: string | null }>(connection: T | null) {
  if (!connection) return null;
  const { credentialCiphertext: _secret, ...safe } = connection;
  return safe;
}

function publicFunnel<T extends { espConnection?: ({ credentialCiphertext?: string | null } | null); metrics?: Array<Record<string, unknown>> }>(funnel: T) {
  const metrics = funnel.metrics ?? [];
  type PerformanceTotals = { views: number; optIns: number; downloads: number; emailsDelivered: number; emailOpens: number; emailClicks: number };
  const totals = metrics.reduce<PerformanceTotals>((sum, row) => ({
    views: sum.views + Number(row.views ?? 0), optIns: sum.optIns + Number(row.optIns ?? 0), downloads: sum.downloads + Number(row.downloads ?? 0),
    emailsDelivered: sum.emailsDelivered + Number(row.emailsDelivered ?? 0), emailOpens: sum.emailOpens + Number(row.emailOpens ?? 0), emailClicks: sum.emailClicks + Number(row.emailClicks ?? 0),
  }), { views: 0, optIns: 0, downloads: 0, emailsDelivered: 0, emailOpens: 0, emailClicks: 0 });
  const performance = { ...totals, conversionRate: totals.views ? Number(((totals.optIns / totals.views) * 100).toFixed(2)) : 0, openRate: totals.emailsDelivered ? Number(((totals.emailOpens / totals.emailsDelivered) * 100).toFixed(2)) : 0, clickRate: totals.emailsDelivered ? Number(((totals.emailClicks / totals.emailsDelivered) * 100).toFixed(2)) : 0 };
  return { ...funnel, espConnection: publicConnection(funnel.espConnection ?? null), performance, optimizationRecommendations: leadFunnelOptimizationRecommendations(performance, Number((funnel as { conversionTarget?: number }).conversionTarget ?? 5)) };
}

export function leadFunnelOptimizationRecommendations(performance: { views: number; optIns: number; conversionRate: number; openRate: number; clickRate: number }, target: number) {
  const rows: Array<{ priority: string; title: string; why: string; action: string }> = [];
  if (performance.views < 100) rows.push({ priority: "medium", title: "Collect a reliable traffic sample", why: `Only ${performance.views} views are recorded, so conversion conclusions are premature.`, action: "Drive at least 100 qualified visits before choosing a winning variation." });
  if (performance.views >= 30 && performance.conversionRate < target) rows.push({ priority: "high", title: "Test the headline and form friction", why: `${performance.conversionRate}% conversion is below the ${target}% target.`, action: "Run the strongest saved headline variation and remove non-essential form fields." });
  if (performance.openRate > 0 && performance.openRate < 30) rows.push({ priority: "medium", title: "Improve delivery-email opens", why: `${performance.openRate}% of delivered emails were opened.`, action: "Test a benefit-led subject line and confirm sender recognition." });
  if (performance.openRate >= 30 && performance.clickRate < 3) rows.push({ priority: "medium", title: "Strengthen the email next step", why: "People open the email but rarely click.", action: "Move one clear CTA above the fold and align it with the lead magnet promise." });
  if (!rows.length) rows.push({ priority: "low", title: "Keep the current funnel and test one variable", why: "No high-confidence performance problem is visible yet.", action: "Test only one headline, CTA, or form variation at a time." });
  return rows;
}

async function contextProject(req: Request, permission?: string) {
  const context = await workspaceContext(req);
  if (permission && !hasWorkspacePermission(context, permission)) throw Object.assign(new Error("Insufficient workspace permission."), { statusCode: 403 });
  if (!await canAccessProject(context, req.params.projectId)) throw Object.assign(new Error("Project not found or unavailable."), { statusCode: 404 });
  const project = await prisma.project.findUnique({ where: { id: req.params.projectId }, include: { businessProfile: true, strategyPlans: { orderBy: { version: "desc" }, take: 1 }, keywordGroups: { where: { status: "approved" } }, website: true } });
  if (!project) throw Object.assign(new Error("Project not found or unavailable."), { statusCode: 404 });
  return { context, project };
}

function encryptionKey() { return createHash("sha256").update(`${config.jwtSecret}:lead-magnet-esp:v1`).digest(); }
function encryptCredential(value: string) { const iv = randomBytes(12); const cipher = createCipheriv("aes-256-gcm", encryptionKey(), iv); const body = Buffer.concat([cipher.update(value, "utf8"), cipher.final()]); return ["v1", iv.toString("base64url"), cipher.getAuthTag().toString("base64url"), body.toString("base64url")].join("."); }
function decryptCredential(value: string) { const [, iv, tag, body] = value.split("."); const decipher = createDecipheriv("aes-256-gcm", encryptionKey(), Buffer.from(iv, "base64url")); decipher.setAuthTag(Buffer.from(tag, "base64url")); return Buffer.concat([decipher.update(Buffer.from(body, "base64url")), decipher.final()]).toString("utf8"); }
function credentialHint(token: string) { return token.length < 9 ? "••••" : `${token.slice(0, 4)}••••${token.slice(-4)}`; }

function privateAddress(address: string) {
  if (address === "::1" || address === "::" || /^f[cd]/i.test(address) || /^fe[89ab]/i.test(address)) return true;
  if (!isIP(address)) return true; if (address.includes(":")) return false;
  const [a, b] = address.split(".").map(Number); return a === 10 || a === 127 || a === 0 || (a === 169 && b === 254) || (a === 172 && b >= 16 && b <= 31) || (a === 192 && b === 168) || (a === 100 && b >= 64 && b <= 127);
}
async function safePublicUrl(raw: string) { const url = new URL(raw); if (url.protocol !== "https:") throw new Error("The webhook must use HTTPS."); const addresses = await lookup(url.hostname, { all: true }); if (!addresses.length || addresses.some((entry) => privateAddress(entry.address))) throw new Error("The webhook resolves to a private or unsafe address."); return url; }
async function providerFetch(url: string, init: RequestInit) { const response = await fetch(url, { ...init, signal: AbortSignal.timeout(12_000) }); const text = await response.text(); const body = text ? (() => { try { return JSON.parse(text); } catch { return { message: text.slice(0, 500) }; } })() : {}; if (!response.ok) throw new Error(`${response.status}: ${String(body?.detail ?? body?.message ?? body?.title ?? "Provider rejected the request")}`); return body; }

async function verifyConnection(input: z.infer<typeof connectionSchema>, project: { name: string; businessName: string | null; businessLocationJson: Prisma.JsonValue | null }, ownerEmail: string) {
  const token = input.token ?? "";
  if (input.provider === "generic_webhook") { const url = await safePublicUrl(input.endpointUrl!); await providerFetch(url.toString(), { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ event: "senuke.verify", project: project.name, timestamp: new Date().toISOString() }) }); return { accountId: null, listId: input.listId ?? null, endpointUrl: url.toString() }; }
  if (!token) throw new Error("An API key or OAuth access token is required.");
  if (input.provider === "mailchimp") {
    const dc = token.split("-").pop(); if (!dc || dc === token) throw new Error("Mailchimp API keys must include their data-center suffix, such as -us21.");
    const base = `https://${dc}.api.mailchimp.com/3.0`; await providerFetch(`${base}/ping`, { headers: { Authorization: `Basic ${Buffer.from(`senuke:${token}`).toString("base64")}` } });
    let listId = input.listId; if (!listId) { const lists = await providerFetch(`${base}/lists?count=1`, { headers: { Authorization: `Basic ${Buffer.from(`senuke:${token}`).toString("base64")}` } }); listId = lists?.lists?.[0]?.id; }
    if (!listId) { const location = jsonObject(project.businessLocationJson); const created = await providerFetch(`${base}/lists`, { method: "POST", headers: { Authorization: `Basic ${Buffer.from(`senuke:${token}`).toString("base64")}`, "Content-Type": "application/json" }, body: JSON.stringify({ name: input.listName, contact: { company: project.businessName || project.name, address1: String(location.streetAddress ?? "Not provided"), city: String(location.city ?? "Not provided"), state: String(location.stateProvince ?? "Not provided"), zip: String(location.postalCode ?? "00000"), country: String(location.country ?? "US") }, permission_reminder: `You requested information from ${project.businessName || project.name}.`, campaign_defaults: { from_name: project.businessName || project.name, from_email: ownerEmail, subject: input.listName, language: "en" }, email_type_option: false }) }); listId = created.id; }
    return { accountId: dc, listId, endpointUrl: base };
  }
  if (input.provider === "brevo") { const headers = { "api-key": token, "Content-Type": "application/json" }; const account = await providerFetch("https://api.brevo.com/v3/account", { headers }); let listId = input.listId; if (!listId) { const created = await providerFetch("https://api.brevo.com/v3/contacts/lists", { method: "POST", headers, body: JSON.stringify({ name: input.listName, folderId: 1 }) }); listId = String(created.id); } return { accountId: String(account.email ?? ownerEmail), listId, endpointUrl: "https://api.brevo.com/v3" }; }
  if (input.provider === "aweber") { const accounts = await providerFetch("https://api.aweber.com/1.0/accounts", { headers: { Authorization: `Bearer ${token}`, Accept: "application/json" } }); const accountId = input.accountId || String(accounts?.entries?.[0]?.id ?? ""); if (!accountId) throw new Error("No AWeber account was available for this token."); const lists = await providerFetch(`https://api.aweber.com/1.0/accounts/${accountId}/lists`, { headers: { Authorization: `Bearer ${token}`, Accept: "application/json" } }); const listId = input.listId || String(lists?.entries?.[0]?.id ?? ""); if (!listId) throw new Error("Create an AWeber list first, then enter its list ID."); return { accountId, listId, endpointUrl: "https://api.aweber.com/1.0" }; }
  const headers = { "X-Auth-Token": `api-key ${token}`, "Content-Type": "application/json" }; await providerFetch("https://api.getresponse.com/v3/accounts", { headers }); let listId = input.listId; if (!listId) { const created = await providerFetch("https://api.getresponse.com/v3/campaigns", { method: "POST", headers, body: JSON.stringify({ name: input.listName }) }); listId = created.campaignId; } return { accountId: input.accountId ?? null, listId, endpointUrl: "https://api.getresponse.com/v3" };
}

async function addSubscriber(connection: { provider: string; credentialCiphertext: string | null; endpointUrl: string | null; accountId: string | null; listId: string | null; fieldMappingsJson: Prisma.JsonValue }, subscriber: z.infer<typeof subscribeSchema>, funnelId: string) {
  if (!connection.credentialCiphertext && connection.provider !== "generic_webhook") throw new Error("ESP credentials are unavailable."); const token = connection.credentialCiphertext ? decryptCredential(connection.credentialCiphertext) : "";
  if (connection.provider === "generic_webhook") { const url = await safePublicUrl(connection.endpointUrl!); await providerFetch(url.toString(), { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ event: "lead.created", funnelId, subscriber }) }); return; }
  if (connection.provider === "mailchimp") { const hash = createHash("md5").update(subscriber.email.toLowerCase()).digest("hex"); await providerFetch(`${connection.endpointUrl}/lists/${connection.listId}/members/${hash}`, { method: "PUT", headers: { Authorization: `Basic ${Buffer.from(`senuke:${token}`).toString("base64")}`, "Content-Type": "application/json" }, body: JSON.stringify({ email_address: subscriber.email, status_if_new: "subscribed", merge_fields: { FNAME: subscriber.firstName ?? "", LNAME: subscriber.lastName ?? "" } }) }); return; }
  if (connection.provider === "brevo") { await providerFetch("https://api.brevo.com/v3/contacts", { method: "POST", headers: { "api-key": token, "Content-Type": "application/json" }, body: JSON.stringify({ email: subscriber.email, attributes: { FIRSTNAME: subscriber.firstName ?? "", LASTNAME: subscriber.lastName ?? "" }, listIds: [Number(connection.listId)], updateEnabled: true }) }); return; }
  if (connection.provider === "aweber") { await providerFetch(`https://api.aweber.com/1.0/accounts/${connection.accountId}/lists/${connection.listId}/subscribers`, { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ email: subscriber.email, name: [subscriber.firstName, subscriber.lastName].filter(Boolean).join(" ") }) }); return; }
  await providerFetch("https://api.getresponse.com/v3/contacts", { method: "POST", headers: { "X-Auth-Token": `api-key ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ email: subscriber.email, name: [subscriber.firstName, subscriber.lastName].filter(Boolean).join(" "), campaign: { campaignId: connection.listId } }) });
}

leadMagnetsRouter.get("/projects/:projectId/lead-magnets", async (req, res, next) => { try {
  const { context, project } = await contextProject(req); const clientViewer = context.roles.size === 1 && context.roles.has("client_viewer");
  const funnels = await prisma.leadMagnetFunnel.findMany({ where: { projectId: project.id, ...(clientViewer ? { status: "published", sharedWithClient: true } : {}) }, orderBy: { version: "desc" }, include: includeFunnel });
  const connections = clientViewer ? [] : await prisma.leadMagnetEspConnection.findMany({ where: { projectId: project.id }, orderBy: { updatedAt: "desc" } });
  res.json({ project: { id: project.id, name: project.name }, funnels: funnels.map(publicFunnel), current: funnels[0] ? publicFunnel(funnels[0]) : null, connections: connections.map(publicConnection), capabilities: { canGenerate: hasWorkspacePermission(context, "run_ai_analysis"), canEdit: hasWorkspacePermission(context, "edit_assigned_work"), canApprove: hasWorkspacePermission(context, "approve"), canManageIntegration: hasWorkspacePermission(context, "manage_integrations"), canPublish: hasWorkspacePermission(context, "publish"), readOnly: !hasWorkspacePermission(context, "edit_assigned_work"), clientViewer } });
} catch (error) { next(error); } });

leadMagnetsRouter.get("/projects/:projectId/lead-magnets/recommendations", async (req, res, next) => { try {
  const { project } = await contextProject(req); const text = `${project.projectType} ${project.niche} ${project.primaryGoal} ${project.businessProfile?.offerSummary} ${project.businessProfile?.targetAudience}`.toLowerCase();
  const candidates = [
    { type: /ecommerce|shopify|store|sale/.test(text) ? "Coupon or Discount" : /saas|software|calculator|automation/.test(text) ? "Calculator" : "Checklist", base: 91 },
    { type: /audit|proposal|agency/.test(text) ? "PDF Report" : /template|workflow|process/.test(text) ? "Template" : "Guide", base: 86 },
    { type: /trial|saas|software/.test(text) ? "Free Trial" : /authority|content|education/.test(text) ? "Email Course" : "Case Study", base: 81 },
  ];
  res.json({ recommendations: candidates.map((item, index) => ({ ...item, score: Math.min(97, item.base + (project.primaryGoal ? 2 : 0)), title: `${project.businessName || project.name} ${item.type}`, why: `${item.type} matches the saved offer, audience, ${project.primaryGoal || "business goal"}, brand context, and conversion path.`, expectedOutcome: index === 0 ? "Highest predicted opt-in fit from the current project evidence." : "A useful alternative for testing format and intent." })) });
} catch (error) { next(error); } });

leadMagnetsRouter.patch("/projects/:projectId/lead-magnets/:funnelId", async (req, res, next) => { try {
  const input = editSchema.parse(req.body ?? {}); const { context, project } = await contextProject(req, "edit_assigned_work"); const funnel = await prisma.leadMagnetFunnel.findFirst({ where: { id: req.params.funnelId, projectId: project.id }, include: includeFunnel }); if (!funnel) return res.status(404).json({ error: "Lead funnel not found." });
  const landing = { ...jsonObject(funnel.landingPageJson), ...(input.landingHeadline ? { headline: input.landingHeadline } : {}), ...(input.landingSubheadline ? { subheadline: input.landingSubheadline } : {}), ...(input.ctaText ? { ctaText: input.ctaText } : {}) };
  const form = { ...jsonObject(funnel.optInFormJson), ...(input.ctaText ? { submitLabel: input.ctaText } : {}) };
  const delivery = { ...jsonObject(funnel.deliveryEmailJson), ...(input.deliverySubject ? { subject: input.deliverySubject } : {}), ...(input.deliveryBody ? { body: input.deliveryBody } : {}) };
  const protectedVersion = ["approved", "published", "superseded"].includes(funnel.status); const latest = protectedVersion ? await prisma.leadMagnetFunnel.findFirst({ where: { projectId: project.id }, orderBy: { version: "desc" }, select: { version: true } }) : null;
  const result = await prisma.$transaction(async (tx) => {
    const data = { title: input.title ?? funnel.title, magnetType: input.magnetType ?? funnel.magnetType, landingPageJson: landing as Prisma.InputJsonValue, optInFormJson: form as Prisma.InputJsonValue, deliveryEmailJson: delivery as Prisma.InputJsonValue, conversionTarget: input.conversionTarget ?? funnel.conversionTarget, sharedWithClient: input.sharedWithClient ?? funnel.sharedWithClient, status: "draft", approvedAt: null, approvedByUserId: null, validationJson: { valid: false, state: "edited", requiredBeforePublish: ["approval", "verified_esp", "link_check", "form_check", "download_check"] } as Prisma.InputJsonValue };
    const row = protectedVersion
      ? await tx.leadMagnetFunnel.create({ data: { projectId: project.id, clientId: project.clientId, version: (latest?.version ?? funnel.version) + 1, ...data, recommendationScore: funnel.recommendationScore, recommendationReason: funnel.recommendationReason, audience: funnel.audience, primaryGoal: funnel.primaryGoal, brandVoice: funnel.brandVoice, assetJson: funnel.assetJson as Prisma.InputJsonValue, thankYouPageJson: funnel.thankYouPageJson as Prisma.InputJsonValue, followUpSequenceJson: funnel.followUpSequenceJson as Prisma.InputJsonValue, abTestsJson: funnel.abTestsJson as Prisma.InputJsonValue, seoMetadataJson: funnel.seoMetadataJson as Prisma.InputJsonValue, trackingPlanJson: funnel.trackingPlanJson as Prisma.InputJsonValue, aiContentGenerationId: funnel.aiContentGenerationId, espConnectionId: funnel.espConnectionId, createdByUserId: context.membership.userId }, include: includeFunnel })
      : await tx.leadMagnetFunnel.update({ where: { id: funnel.id }, data, include: includeFunnel });
    await tx.leadMagnetDecision.create({ data: { funnelId: row.id, actorUserId: context.membership.userId, decision: protectedVersion ? "revised_as_new_version" : "edited", comments: input.comments, snapshotJson: { sourceVersion: funnel.version, version: row.version, changedFields: Object.keys(input) } } });
    await tx.executionTask.updateMany({ where: { projectId: project.id, moduleName: "lead_magnet", relatedAssetId: funnel.id, status: { notIn: ["published", "completed"] } }, data: { relatedAssetId: row.id, status: "needs_review", approvedAt: null, approvalDecision: null, actionButtonLabel: "Review Lead Funnel", relatedUrl: `/lead-magnets?projectId=${project.id}` } });
    await recordWorkspaceActivity(tx, { context, action: protectedVersion ? "lead_magnet.version_created_from_edit" : "lead_magnet.edited", entityType: "lead_magnet_funnel", entityId: row.id, agencyClientId: project.agencyClientId, projectId: project.id, previousJson: { sourceId: funnel.id, version: funnel.version, status: funnel.status }, nextJson: { version: row.version, status: "draft", changedFields: Object.keys(input), comments: input.comments } }); return row;
  }); res.json({ funnel: publicFunnel(result) });
} catch (error) { next(error); } });

leadMagnetsRouter.post("/projects/:projectId/lead-magnets/:funnelId/approve", async (req, res, next) => { try {
  const input = decisionSchema.parse(req.body ?? {}); const { context, project } = await contextProject(req, "approve"); const funnel = await prisma.leadMagnetFunnel.findFirst({ where: { id: req.params.funnelId, projectId: project.id } }); if (!funnel) return res.status(404).json({ error: "Lead funnel not found." });
  const result = await prisma.$transaction(async (tx) => { await tx.leadMagnetFunnel.updateMany({ where: { projectId: project.id, status: "approved", id: { not: funnel.id } }, data: { status: "superseded" } }); const row = await tx.leadMagnetFunnel.update({ where: { id: funnel.id }, data: { status: "approved", approvedAt: new Date(), approvedByUserId: context.membership.userId, sharedWithClient: input.shareWithClient ?? funnel.sharedWithClient }, include: includeFunnel }); await tx.leadMagnetDecision.create({ data: { funnelId: row.id, actorUserId: context.membership.userId, decision: "approved", comments: input.comments, snapshotJson: { version: row.version, type: row.magnetType } } }); await tx.executionTask.updateMany({ where: { projectId: project.id, moduleName: "lead_magnet", relatedAssetId: funnel.id, status: { notIn: ["completed", "published"] } }, data: { status: "ready_to_publish", approvedAt: new Date(), approvalDecision: "approved", approvalNotes: input.comments ?? null, approverMembershipId: context.membership.id, actionButtonLabel: "Publish Lead Funnel", relatedUrl: `/lead-magnets?projectId=${project.id}` } }); await recordWorkspaceActivity(tx, { context, action: "lead_magnet.approved", entityType: "lead_magnet_funnel", entityId: row.id, agencyClientId: project.agencyClientId, projectId: project.id, previousJson: { status: funnel.status }, nextJson: { status: "approved", version: row.version, executionTaskStatus: "ready_to_publish" } }); const recipients = await tx.workspaceMembership.findMany({ where: { workspaceId: context.workspace.id, status: "active", roles: { some: { role: { in: ["owner", "admin", "manager", "approver", "editor"] } } } }, select: { userId: true } }); for (const userId of [...new Set(recipients.map((item) => item.userId))]) await createWorkspaceNotification(tx, { context, userId, type: "lead_magnet_approved", title: "Lead funnel approved", body: `${project.name}: ${row.title} was approved and is ready for ESP validation and publishing.`, actionUrl: `/lead-magnets?projectId=${project.id}`, agencyClientId: project.agencyClientId, projectId: project.id }); return row; }); res.json({ funnel: publicFunnel(result) });
} catch (error) { next(error); } });

leadMagnetsRouter.post("/projects/:projectId/lead-magnets/:funnelId/reject", async (req, res, next) => { try {
  const input = decisionSchema.extend({ comments: z.string().trim().min(3).max(4000) }).parse(req.body ?? {}); const { context, project } = await contextProject(req, "approve"); const funnel = await prisma.leadMagnetFunnel.findFirst({ where: { id: req.params.funnelId, projectId: project.id } }); if (!funnel) return res.status(404).json({ error: "Lead funnel not found." });
  const row = await prisma.$transaction(async (tx) => { const updated = await tx.leadMagnetFunnel.update({ where: { id: funnel.id }, data: { status: "changes_requested", approvedAt: null, approvedByUserId: null }, include: includeFunnel }); await tx.leadMagnetDecision.create({ data: { funnelId: funnel.id, actorUserId: context.membership.userId, decision: "changes_requested", comments: input.comments } }); await tx.executionTask.updateMany({ where: { projectId: project.id, moduleName: "lead_magnet", relatedAssetId: funnel.id }, data: { status: "changes_requested", changesRequestedAt: new Date(), approvalDecision: "changes_requested", approvalNotes: input.comments } }); await recordWorkspaceActivity(tx, { context, action: "lead_magnet.changes_requested", entityType: "lead_magnet_funnel", entityId: funnel.id, agencyClientId: project.agencyClientId, projectId: project.id, nextJson: { comments: input.comments, executionTaskStatus: "changes_requested" } }); if (funnel.createdByUserId) await createWorkspaceNotification(tx, { context, userId: funnel.createdByUserId, type: "lead_magnet_changes_requested", title: "Lead funnel changes requested", body: `${project.name}: ${input.comments}`, actionUrl: `/lead-magnets?projectId=${project.id}`, agencyClientId: project.agencyClientId, projectId: project.id }); return updated; }); res.json({ funnel: publicFunnel(row) });
} catch (error) { next(error); } });

leadMagnetsRouter.post("/projects/:projectId/lead-magnets/esp/connect", async (req, res, next) => { try {
  const input = connectionSchema.parse(req.body ?? {}); if (input.provider === "generic_webhook" && !input.endpointUrl) return res.status(400).json({ error: "A Generic Webhook URL is required." }); const { context, project } = await contextProject(req, "manage_integrations"); const owner = await prisma.user.findUnique({ where: { id: context.workspace.ownerUserId }, select: { email: true } });
  try { const verified = await verifyConnection(input, project, owner?.email ?? "no-reply@senuke.com"); const row = await prisma.$transaction(async (tx) => { const connection = await tx.leadMagnetEspConnection.upsert({ where: { projectId_provider: { projectId: project.id, provider: input.provider } }, update: { status: "connected", accountId: verified.accountId, listId: verified.listId, listName: input.listName, endpointUrl: verified.endpointUrl, fieldMappingsJson: input.fieldMappings, ...(input.token ? { credentialCiphertext: encryptCredential(input.token), credentialHint: credentialHint(input.token) } : {}), lastVerifiedAt: new Date(), errorMessage: null }, create: { projectId: project.id, clientId: project.clientId, provider: input.provider, status: "connected", accountId: verified.accountId, listId: verified.listId, listName: input.listName, endpointUrl: verified.endpointUrl, fieldMappingsJson: input.fieldMappings, credentialCiphertext: input.token ? encryptCredential(input.token) : null, credentialHint: input.token ? credentialHint(input.token) : null, lastVerifiedAt: new Date(), createdByUserId: context.membership.userId } }); await recordWorkspaceActivity(tx, { context, action: "lead_magnet.esp_connected", entityType: "lead_magnet_esp_connection", entityId: connection.id, agencyClientId: project.agencyClientId, projectId: project.id, nextJson: { provider: connection.provider, listId: connection.listId, verifiedAt: connection.lastVerifiedAt } }); return connection; }); return res.json({ connection: publicConnection(row) }); }
  catch (error) { const message = error instanceof Error ? error.message : "Connection verification failed."; await prisma.$transaction(async (tx) => { const failed = await tx.leadMagnetEspConnection.upsert({ where: { projectId_provider: { projectId: project.id, provider: input.provider } }, update: { status: "failed", errorMessage: message }, create: { projectId: project.id, clientId: project.clientId, provider: input.provider, status: "failed", listName: input.listName, endpointUrl: input.endpointUrl, fieldMappingsJson: input.fieldMappings, errorMessage: message, createdByUserId: context.membership.userId } }); await recordWorkspaceActivity(tx, { context, action: "lead_magnet.esp_connection_failed", entityType: "lead_magnet_esp_connection", entityId: failed.id, agencyClientId: project.agencyClientId, projectId: project.id, nextJson: { provider: input.provider, error: message } }); await createWorkspaceNotification(tx, { context, userId: context.workspace.ownerUserId, type: "esp_connection_failed", title: "Email service connection failed", body: `${project.name}: ${input.provider} could not be verified. ${message}`, actionUrl: `/lead-magnets?projectId=${project.id}`, agencyClientId: project.agencyClientId, projectId: project.id }); }); return res.status(409).json({ error: message }); }
} catch (error) { next(error); } });

leadMagnetsRouter.post("/projects/:projectId/lead-magnets/:funnelId/publish", async (req, res, next) => { try {
  const { context, project } = await contextProject(req, "publish"); const connectionId = z.object({ connectionId: z.string().cuid().optional(), shareWithClient: z.boolean().optional() }).parse(req.body ?? {}); const funnel = await prisma.leadMagnetFunnel.findFirst({ where: { id: req.params.funnelId, projectId: project.id }, include: { espConnection: true } }); if (!funnel) return res.status(404).json({ error: "Lead funnel not found." });
  const connection = connectionId.connectionId ? await prisma.leadMagnetEspConnection.findFirst({ where: { id: connectionId.connectionId, projectId: project.id, status: "connected" } }) : funnel.espConnection; const errors: string[] = []; if (funnel.status !== "approved") errors.push("Approve this funnel before publishing."); if (!connection || connection.status !== "connected" || !connection.lastVerifiedAt) errors.push("Connect and verify an email service before publishing."); if (!jsonObject(funnel.assetJson).title && !funnel.title) errors.push("Lead magnet content is missing."); if (!jsonObject(funnel.landingPageJson).headline) errors.push("Landing-page headline is missing."); if (!jsonList(funnel.followUpSequenceJson).length) errors.push("Follow-up email sequence is missing."); if (!jsonList(jsonObject(funnel.optInFormJson).fields).some((field) => String(jsonObject(field).type).toLowerCase() === "email" || String(jsonObject(field).name).toLowerCase() === "email")) errors.push("The opt-in form must include an email field.");
  if (errors.length) { await prisma.$transaction((tx) => recordWorkspaceActivity(tx, { context, action: "lead_magnet.publish_validation_failed", entityType: "lead_magnet_funnel", entityId: funnel.id, agencyClientId: project.agencyClientId, projectId: project.id, nextJson: { errors } })); return res.status(409).json({ error: errors.join(" "), errors }); }
  const publicSlug = funnel.publicSlug || `${slug(project.name)}-${slug(funnel.title)}-${randomBytes(4).toString("hex")}`; const publicUrl = `${config.webAppUrl.replace(/\/$/, "")}/lead/${publicSlug}`;
  const row = await prisma.$transaction(async (tx) => { const updated = await tx.leadMagnetFunnel.update({ where: { id: funnel.id }, data: { status: "published", espConnectionId: connection!.id, publicSlug, publicUrl, publishedAt: new Date(), sharedWithClient: connectionId.shareWithClient ?? funnel.sharedWithClient, validationJson: { valid: true, checkedAt: new Date().toISOString(), checks: ["approved", "asset", "landing_page", "email_field", "email_sequence", "esp_verified"] } }, include: includeFunnel }); await tx.leadMagnetDecision.create({ data: { funnelId: funnel.id, actorUserId: context.membership.userId, decision: "published", snapshotJson: { publicUrl, espProvider: connection!.provider } } }); await tx.executionTask.updateMany({ where: { projectId: project.id, moduleName: "lead_magnet", relatedAssetId: funnel.id }, data: { status: "published", publishedAt: new Date(), completedAt: new Date(), actionButtonLabel: "Open Live Funnel", relatedUrl: publicUrl } }); await recordWorkspaceActivity(tx, { context, action: "lead_magnet.published", entityType: "lead_magnet_funnel", entityId: funnel.id, agencyClientId: project.agencyClientId, projectId: project.id, nextJson: { publicUrl, provider: connection!.provider, verified: true, executionTaskStatus: "published" } }); await createWorkspaceNotification(tx, { context, userId: context.workspace.ownerUserId, type: "lead_magnet_published", title: "Lead funnel published", body: `${project.name}'s ${funnel.title} is published and connected to ${connection!.provider}.`, actionUrl: `/lead-magnets?projectId=${project.id}`, agencyClientId: project.agencyClientId, projectId: project.id }); return updated; }); res.json({ funnel: publicFunnel(row) });
} catch (error) { next(error); } });

leadMagnetsRouter.post("/projects/:projectId/lead-magnets/:funnelId/metrics", async (req, res, next) => { try {
  const input = metricsSchema.parse(req.body ?? {}); const { context, project } = await contextProject(req, "edit_assigned_work"); const funnel = await prisma.leadMagnetFunnel.findFirst({ where: { id: req.params.funnelId, projectId: project.id } }); if (!funnel) return res.status(404).json({ error: "Lead funnel not found." }); const conversionRate = input.views ? input.optIns / input.views * 100 : 0; const openRate = input.emailsDelivered ? input.emailOpens / input.emailsDelivered * 100 : 0; const clickRate = input.emailsDelivered ? input.emailClicks / input.emailsDelivered * 100 : 0;
  await prisma.$transaction(async (tx) => { await tx.leadMagnetMetricSnapshot.create({ data: { funnelId: funnel.id, ...input, conversionRate, openRate, clickRate } }); await recordWorkspaceActivity(tx, { context, action: "lead_magnet.performance_updated", entityType: "lead_magnet_funnel", entityId: funnel.id, agencyClientId: project.agencyClientId, projectId: project.id, nextJson: { ...input, conversionRate, openRate, clickRate } }); if (input.views >= 30 && (conversionRate >= funnel.conversionTarget * 2 || conversionRate < funnel.conversionTarget * .5)) { await tx.leadMagnetFunnel.update({ where: { id: funnel.id }, data: { lastPerformanceAlertAt: new Date(), lastOptimizationAt: new Date() } }); await createWorkspaceNotification(tx, { context, userId: context.workspace.ownerUserId, type: conversionRate >= funnel.conversionTarget * 2 ? "lead_magnet_high_conversion" : "lead_magnet_conversion_drop", title: conversionRate >= funnel.conversionTarget * 2 ? "High lead-funnel conversion" : "Lead-funnel conversion needs attention", body: `${funnel.title} converted at ${conversionRate.toFixed(1)}% against a ${funnel.conversionTarget.toFixed(1)}% target.`, actionUrl: `/lead-magnets?projectId=${project.id}`, agencyClientId: project.agencyClientId, projectId: project.id }); } }); const updated = await prisma.leadMagnetFunnel.findUniqueOrThrow({ where: { id: funnel.id }, include: includeFunnel }); res.json({ funnel: publicFunnel(updated) });
} catch (error) { next(error); } });

const publicRate = new Map<string, { count: number; resetAt: number }>();
function publicAllowed(req: Request) { const key = req.ip || "unknown"; const now = Date.now(); const state = publicRate.get(key); if (!state || state.resetAt < now) { publicRate.set(key, { count: 1, resetAt: now + 60_000 }); return true; } state.count += 1; return state.count <= 30; }
publicLeadMagnetsRouter.get("/lead-magnets/:slug", async (req, res, next) => { try { if (!publicAllowed(req)) return res.status(429).json({ error: "Too many requests." }); const funnel = await prisma.leadMagnetFunnel.findFirst({ where: { publicSlug: req.params.slug, status: "published" }, include: { espConnection: true } }); if (!funnel) return res.status(404).json({ error: "Lead funnel not found." }); await prisma.leadMagnetMetricSnapshot.create({ data: { funnelId: funnel.id, source: "public_page", views: 1 } }); res.json({ funnel: { id: funnel.id, title: funnel.title, magnetType: funnel.magnetType, landingPage: funnel.landingPageJson, optInForm: funnel.optInFormJson, thankYouPage: funnel.thankYouPageJson, seoMetadata: funnel.seoMetadataJson } }); } catch (error) { next(error); } });
publicLeadMagnetsRouter.post("/lead-magnets/:slug/subscribe", async (req, res, next) => { try { if (!publicAllowed(req)) return res.status(429).json({ error: "Too many requests." }); const input = subscribeSchema.parse(req.body ?? {}); const funnel = await prisma.leadMagnetFunnel.findFirst({ where: { publicSlug: req.params.slug, status: "published" }, include: { espConnection: true } }); if (!funnel?.espConnection || funnel.espConnection.status !== "connected") return res.status(409).json({ error: "Lead delivery is temporarily unavailable." }); await addSubscriber(funnel.espConnection, input, funnel.id); const email = jsonObject(funnel.deliveryEmailJson); await sendMail({ to: input.email, subject: String(email.subject ?? `Your ${funnel.title}`), text: String(email.body ?? `Thank you. Your ${funnel.title} is ready.`), html: `<div style="font-family:Arial,sans-serif;max-width:640px;margin:auto;line-height:1.6"><h1>${String(email.subject ?? funnel.title)}</h1><p>${String(email.body ?? "Thank you for requesting this resource.").replace(/\n/g, "<br>")}</p></div>` }); await prisma.leadMagnetMetricSnapshot.create({ data: { funnelId: funnel.id, source: "public_opt_in", optIns: 1, downloads: 1, emailsDelivered: 1, metadataJson: { emailHash: createHmac("sha256", config.jwtSecret).update(input.email.toLowerCase()).digest("hex") } } }); res.status(201).json({ thankYouPage: funnel.thankYouPageJson, asset: funnel.assetJson }); } catch (error) { next(error); } });
