import {beforeEach,expect,it,vi} from 'vitest';
const mocks=vi.hoisted(()=>({release:vi.fn(),credential:vi.fn(),verify:vi.fn(),mail:vi.fn()}));
vi.mock('@webtummy/db',()=>({prisma:{websiteApprovedRelease:{findFirst:mocks.release},websiteRecaptchaCredential:{findFirst:mocks.credential}}}));
vi.mock('../website-recaptcha.js',()=>({verifyWebsiteRecaptcha:mocks.verify}));vi.mock('../email.js',()=>({sendMail:mocks.mail}));
import {publicWebsiteFormsRouter,staticWebsiteFormAction} from './website-public-forms.js';
const model={identity:{businessName:'Example',contactEmail:'test@example.com'},forms:[{destination:'test@example.com',fields:[]}],pages:[],recaptcha:{credentialId:'c',siteKey:'site',hostname:'example.com'}};
beforeEach(()=>{vi.resetAllMocks();mocks.release.mockResolvedValue({id:'r',projectId:'p',snapshotHash:'h',immutableSnapshot:model});mocks.credential.mockResolvedValue({id:'c',secretCiphertext:'encrypted',hostname:'example.com'});});
async function submit(body:Record<string,string>){const token=staticWebsiteFormAction({id:'r',snapshotHash:'h'}).split('/').at(-1);const req={params:{releaseId:'r',token},body,ip:'test'},res:any={status:vi.fn().mockReturnThis(),json:vi.fn().mockReturnThis()},next=vi.fn();const handler=(publicWebsiteFormsRouter as any).stack.find((layer:any)=>layer.route?.path==='/website-forms/:releaseId/:token').route.stack[0].handle;await handler(req,res,next);expect(next).not.toHaveBeenCalled();return res;}
it('rejects unverified submissions before email delivery',async()=>{mocks.verify.mockResolvedValue(false);const res=await submit({'g-recaptcha-response':'bad'});expect(res.status).toHaveBeenCalledWith(400);expect(mocks.mail).not.toHaveBeenCalled();});
it('sends only after the release-scoped credential verifies',async()=>{mocks.verify.mockResolvedValue(true);const res=await submit({'g-recaptcha-response':'good'});expect(mocks.credential).toHaveBeenCalledWith({where:{id:'c',projectId:'p',siteKey:'site',hostname:'example.com'}});expect(mocks.mail).toHaveBeenCalledTimes(1);expect(res.status).toHaveBeenCalledWith(201);});
it('keeps previously approved unprotected forms working',async()=>{mocks.release.mockResolvedValue({id:'r',snapshotHash:'h',projectId:'p',immutableSnapshot:{...model,recaptcha:undefined}});const res=await submit({});expect(res.status).toHaveBeenCalledWith(201);expect(mocks.verify).not.toHaveBeenCalled();});
