import {createHash,createCipheriv,createDecipheriv,randomBytes} from 'node:crypto';
import {config} from './config.js';
const key=()=>createHash('sha256').update(`${config.appEncryptionKey}:website-recaptcha:v1`).digest();
export function encryptRecaptchaSecret(secret:string){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key(),iv);const encrypted=Buffer.concat([cipher.update(secret,'utf8'),cipher.final()]);return ['v1',iv.toString('base64url'),cipher.getAuthTag().toString('base64url'),encrypted.toString('base64url')].join('.');}
export function decryptRecaptchaSecret(value:string){const [version,iv,tag,data]=value.split('.');if(version!=='v1'||!iv||!tag||!data)throw Error('Invalid reCAPTCHA credential');const decipher=createDecipheriv('aes-256-gcm',key(),Buffer.from(iv,'base64url'));decipher.setAuthTag(Buffer.from(tag,'base64url'));return Buffer.concat([decipher.update(Buffer.from(data,'base64url')),decipher.final()]).toString('utf8');}
export function publicRecaptchaSettings(settings:Record<string,unknown>){const r=settings.recaptcha&&typeof settings.recaptcha==='object'?settings.recaptcha as Record<string,unknown>:{};return r.enabled===true&&typeof r.siteKey==='string'&&typeof r.credentialId==='string'&&typeof r.hostname==='string'?{credentialId:r.credentialId,siteKey:r.siteKey,hostname:r.hostname}:undefined;}
export async function verifyWebsiteRecaptcha(token:string,credential:{secretCiphertext:string;hostname:string},fetcher:typeof fetch=fetch){
 if(!token.trim())return false;
 try{const response=await fetcher('https://www.google.com/recaptcha/api/siteverify',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({secret:decryptRecaptchaSecret(credential.secretCiphertext),response:token}),signal:AbortSignal.timeout(10000)});if(!response.ok)return false;const result=await response.json() as {success?:boolean;hostname?:string;challenge_ts?:string};const hostname=(result.hostname||'').toLowerCase(),expected=credential.hostname.toLowerCase();const age=Date.now()-Date.parse(result.challenge_ts||'');return result.success===true&&(hostname===expected||hostname.endsWith(`.${expected}`))&&Number.isFinite(age)&&age>=-30000&&age<=120000;}catch{return false;}
}
